### PR TITLE
feat(cookies): implement cookies across the board

### PR DESCRIPTION
**Pull request by pavelfeldman**

### CODE REVIEW

**Review by dgozman — APPROVED** [review]

**Comment by kblok** [comment]
@pavelfeldman Why did we remove the cookie size here?

**Comment by aslushnikov** [comment]
@kblok IIRC it wasn't needed by anybody and dealt some troubles cross-browser.

**Comment by kblok** [comment]
@aslushnikov 

>Do you think it's important for web devs?

Nope, just comparing APIs. I wanted to know if it was something missing, temporary removed or explicitly removed :p

**Comment by aslushnikov** [comment]
Ah!
Explicitly. :)

**Pull request merged**
