### PR TITLE
feat(webkit): bump to 1530

### PR DESCRIPTION
**Pull request by yury-s**

### CODE REVIEW

**Comment by yury-s** [comment]
cc @q66

**Comment by q66** [comment]
if there are any test failures I will look into them during tomorrow

**Review by mxschmitt — COMMENTED** [review]
Why are you deleting the snapshot?

**Comment by yury-s** [comment]
> Why are you deleting the snapshot?

Reverted.

**Review by mxschmitt — APPROVED** [review]

**Review by aslushnikov — APPROVED** [review]

**Comment by aslushnikov** [comment]
Webkit windows failures are caused by a diffferent cookie LAX treatment that's already present on tip of tree - has nothing to do with this roll: https://devops.aslushnikov.com/flakiness2.html#timestamp=1628715540000&commits=30

LGTM

**Pull request merged**
