### PR TITLE
docs: Add mockiavelli library to Showcase

### PR DESCRIPTION
**Pull request by lukaszfiszer**

### CODE REVIEW

**Review by pavelfeldman — COMMENTED** [review]
Would you be interested in contributing missing features into Playwright instead? We think network routing is essential and that's why we have `route` prominently present in pages and context APIs. I would not want to fork the community into using one or the other.

You have features that are very interesting though, for example `once`. Would love to see it upstream in `route`.

Another aspect is that mocking the network on the page level is on the edge of being an anti-pattern, we prefer emulating on the context level so that popup windows were also covered. That does not seem to be mentioned in the Mockiavelli's docs.

**Comment by lukaszfiszer** [comment]
> Would you be interested in contributing missing features into Playwright instead? We think network routing is essential and that's why we have `route` prominently present in pages and context APIs. I would not want to fork the community into using one or the other.

That's sounds interesting. For the context: we developed Mockiavelli internally at HL Tech about 1.5 year ago. Its purpose was to allowed us to write test for our SPAs with puppeteer. Only recently, before open-sourcing it, we've added support for playwright. We still don't use it with playwright internally, as we were waiting for v1.0. So even if some or all of Mockiavelli features would be merged upstream into Playwright, we would still keep it around for some time for ourselves and other puppeteer users.

> You have features that are very interesting though, for example `once`. Would love to see it upstream in `route`.

What about other features? The purpose of Mockiavelli is primarily to mock RESTful API. As such, it is much more opinionated that `route`:

1) it expect user to specify HTTP method explicitly. Either by providing an object with `method` param to `.mock` method, ot by calling `.mock<HTTP_METHOD>`.
2) it allows to specify query string in matchers as objects
3) all mock methods return `Mock` object that allow to wait and set expectations on requests 
4) once mocking is setup, all XHR and fetch requests are being intercepted. Those not matched by any mock are replied with 404. This is done on purpose to prevent requests hitting real API when app is under test.  

How would you see those 2 APIs merged together?

> Another aspect is that mocking the network on the page level is on the edge of being an anti-pattern, we prefer emulating on the context level so that popup windows were also covered. That does not seem to be mentioned in the Mockiavelli's docs.

Didn't know that. I'll have a look and update the docs and tests accordingly.

**Comment by pavelfeldman** [comment]
That's a great question - I did not notice you were only doing static replies - that could be a solid differentiator that prevents a problem of choice for the users. As you said, you can be more opinionated while being external as well.

Having said that, you obviously have a lot of experience in the space and if you think it applies to the typical `route` user, happy to welcome it upstream. Would need to be case-by-case, but I looked at the api and it seems largely compatible with what we have. For example, expanding on our query language and making responses static can totally work. Same goes for the returned promise.

```js
const responsePromise = await page.route({
    method: 'GET',
    url: '/api/users',
    query: { age: '30' }
}, { status: 200 });
```

The major risk here is baking something too specific too low in the stack, so we need to validate that this works well for the generic user.

**Review by pavelfeldman — APPROVED** [review]

**Comment by pavelfeldman** [comment]
@lukaszfiszer: filed the issue for the discussion ^^

**Comment by lukaszfiszer** [comment]
> That's a great question - I did not notice you were only doing static replies - that could be a solid differentiator that prevents a problem of choice for the users. As you said, you can be more opinionated while being external as well.

Actually, we do functional/dynamic replies as well: https://github.com/hltech/mockiavelli#dynamic-responses. The only difference is that the function receives and return plain request/response objects. This was done to hide the underlying automation library from the user. If merged upstream, this is no longer necessary. 

> 
> Having said that, you obviously have a lot of experience in the space and if you think it applies to the typical `route` user, happy to welcome it upstream. Would need to be case-by-case, but I looked at the api and it seems largely compatible with what we have. For example, expanding on our query language and making responses static can totally work. Same goes for the returned promise.
> 
> ```js
> const responsePromise = await page.route({
>     method: 'GET',
>     url: '/api/users',
>     query: { age: '30' }
> }, { status: 200 });
> ```
> 
> The major risk here is baking something too specific too low in the stack, so we need to validate that this works well for the generic user. 

Agree. Thanks for opening discussion in another issue. If time allows me, I will draft some API proposition there.

**Pull request merged**
