### PR TITLE
Fix unselect issue

### LINKED ISSUE #31290: [Bug]: Unselect isn't recorded by codegen
### Version

1.44.1

### Steps to reproduce

1. `$ npx playwright codegen https://html-preview.github.io/\?url\=https://gist.githubusercontent.com/mtsmfm/a57f12f80fbfbda30ebec8790d760610/raw/002585795a6c1ef5a9f450b386db3618c1c2e8dc/multiselect.html`
2. Click "Dog"
3. Ctrl Click "Dog"

### Expected behavior

It records `selectOption([])`

### Actual behavior

Nothing recorded and codegen stops working

### Additional context

https://github.com/microsoft/playwright/assets/1796864/29d72bc5-ef7b-478c-b5a9-6bed9c4e71cc

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.22 GB / 15.54 GB
    Container: Yes
  Binaries:
    Node: 20.13.1 - ~/.local/share/mise/installs/node/20/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.8.0 - ~/.local/share/mise/installs/node/20/bin/npm
  IDEs:
    VSCode: 1.90.0 - /home/mtsmfm/.vscode-server/bin/89de5a8d4d6205e5b11647eb6a74844ca23d2573/bin/remote-cli/code
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
```

### PR DESCRIPTION
**Pull request by mtsmfm**
Fixes https://github.com/microsoft/playwright/issues/31290

### CODE REVIEW

**Comment by dgozman** [comment]
@mtsmfm Thank you for the PR! Do you think it is ready for review? Note that new tests do not pass on Firefox/WebKit, so I'd recommend to fix them locally first.

**Comment by mtsmfm** [comment]
@dgozman It's still in draft as PR status says. I'll change the status once I fix the failure.

**Comment by pavelfeldman** [comment]
sg, let us know when it is ready via commenting, and it'll pop up in our internal review dashboard. do not reply to this message unless you want us to take a look at the pr!

**Comment by pavelfeldman** [comment]
Archiving due to inactivity for now

**Comment by mtsmfm** [comment]
Sorry I forgot to investigate the failure.

I've re-created a PR.

https://github.com/microsoft/playwright/pull/32127

**Pull request closed without merging**
