### PR TITLE
fix: improve compatibility of using ESM/TS with Deno

### PR DESCRIPTION
**Pull request by nathanwhit**
### 
Deno does not support custom ESM loaders, which playwright uses to provide TS/ESM support. This currently means that deno users cannot use playwright with ESM. However, deno supports running typescript and ESM natively, so disabling the loader allows this to work.

A second small issue is that deno doesn't require a `package.json` file, and defaults to ESM (as opposed to node, which defaults to CommonJS). This means that currently if you don't have a `package.json` file, when running in deno playwright would incorrectly assume the project is commonjs.

Two small changes here:
- Disable the ESM loader when running in deno (as detected by looking for `process.versions.deno`)
- Consider files to be ESM, even without a package.json present, when running in deno

---

Overall this greatly improves the experience when using playwright with deno, and I hope the changes are minimal enough to be acceptable. Thanks for your time!

### CODE REVIEW

**Comment by nathanwhit** [comment]
@microsoft-github-policy-service agree company="Deno Land Inc"

**Comment by dgozman** [comment]
@nathanwhit Thank you for the PR! We expect [custom ESM loaders](https://nodejs.org/api/module.html#customization-hooks) to become stable Node.js API soon, so that's probably some feedback to Deno to implement them and stay compatible with Node.js ecosystem.

For now, we'd prefer not to introduce Deno-specific code, since we haven't seen much interest from the community. I'd recommend to file an issue first, so that we can measure the community interest in supporting Deno.

I'll close this PR for now, since there are no immediate plans to land it. However, we can reopen it later if the Deno support becomes a widely requested feature.

**Comment by nathanwhit** [comment]
I respect the decision, but I would push back a bit on there not being interest – [this issue](https://github.com/microsoft/playwright/issues/3146) requesting deno support from a few years back had dozens of upvotes and people commenting in support of the request.

Would you be open to landing just the one commit? https://github.com/microsoft/playwright/pull/33128/commits/458e6c81fe772d810813849f011a7332ebce6f5c
It's a one line change, and makes a big difference in usability for our users.

**Comment by marvinhagemeister** [comment]
FWIW we keep getting a couple of requests each week in the Deno discord asking for playwright support. We'd love to use playwright ourselves as well to test projects here at Deno. Merging this PR would unblock Deno users on being able to use playwright.

**Comment by dgozman** [comment]
> Would you be open to landing just the one commit? https://github.com/microsoft/playwright/commit/458e6c81fe772d810813849f011a7332ebce6f5c

As a workaround, you can just pass `PW_DISABLE_TS_ESM` environment variable today.

> FWIW we keep getting a couple of requests each week in the Deno discord asking for playwright support.

Could you please file an issue? Unfortunately, it is hard to track requests for Playwright somewhere in Deno discord 😄 However, an issue would be a clear indicator of the interest and a great place for discussion. I assume we are talking exclusively about the recent Deno 2.0 release, and I don't think we've seen it explicitly mentioned on our issue tracker just yet.

> Merging this PR would unblock Deno users on being able to use playwright.

Have you tried running with `PW_DISABLE_TS_ESM`? Is there any feedback? Does everything work? We are hesitant at landing partial support, because it's unclear whether there are more blocks down the road. For example, disabling the custom ESM loader breaks dependencies detection for watch mode, tsx preprocessor, our tsconfig path resolution, etc.

It would be interesting to run Playwright's own tests with deno and see what's passing and what's not. That could help us make an informed decision.

**Comment by eavidy** [comment]
@dgozman I noticed that a PR #38599 related to Bun has been merged recently. Will this PR be reconsidered now?

**Comment by dgozman** [comment]
@eavidy Please file an issue and we'll consider it.

**Pull request closed without merging**
