### PR TITLE
chore(dotnet): add request argument to route handlers

### PR DESCRIPTION
**Pull request by kblok**

### CODE REVIEW

**Review by avodovnik — APPROVED** [review]
I assume the generator renders the output you expect right? LGTM in that case.

**Comment by kblok** [comment]
@avodovnik it does :)

**Review by yury-s — COMMENTED** [review]
We dropped request param in java because it is redundant with `Route.request()`. Can we actually do the same in C# for the sake of simpler API?

**Comment by kblok** [comment]
Great point @yury-s

**Pull request closed without merging**
