### PR TITLE
chore: add iPhone 15 device family

### LINKED ISSUE #31573: [Feature]: Add iPhone 15 devices
### 🚀 Feature Request

I heavily use Playwright and I would love to add iPhone 15 devices.

### Example

_No response_

### Motivation

Need to be able to emulate iPhone 15 devices in Playwright tests.

### PR DESCRIPTION
**Pull request by StanislavGrishaev**
Fixes https://github.com/microsoft/playwright/issues/31573

### CODE REVIEW

**Comment by StanislavGrishaev** [comment]
@microsoft-github-policy-service agree

**Comment by StanislavGrishaev** [comment]
As far as I can see, there is one test failure that has nothing to do with changes in PR (flaky?). I can’t restart the job on my own. I'll tag you here delicately @mxschmitt

**Comment by StanislavGrishaev** [comment]
I'll try to open a new one with the same changes so that the jobs with tests will pass

**Comment by mxschmitt** [comment]
Sorry for the late response! It's on my list, I wanted to use Xcode and compare the values with the viewport values you are using before merging it.

**Comment by StanislavGrishaev** [comment]
> Sorry for the late response! It's on my list, I wanted to use Xcode and compare the values with the viewport values you are using before merging it.

sure, no problem ! I created a new pr to try to successfully complete the jobs - https://github.com/microsoft/playwright/pull/31623

jfyi - I used simulators in Xcode 15.4 + https://whatismyviewport.com/ to determine the values ​​for the code.

**Pull request closed without merging**
