### PR TITLE
chore(dotnet): split unions into multiple overloads

### PR DESCRIPTION
**Pull request by avodovnik**
Splits union arguments into overloads and hides the main function. It keeps the "renamed" argument and also adds the relevant documentation;

Here's an example of `RouteAsync`:

```csharp
/// <summary>
/// <para>
/// Routing provides the capability to modify network requests that are made by any
/// page in the browser context. Once route is enabled, every request matching the url
/// pattern will stall unless it's continued, fulfilled or aborted.
/// </para>
/// <para>An example of a naive handler that aborts all image requests:</para>
/// <para>or the same snippet using a regex pattern instead:</para>
/// <para>
/// It is possible to examine the request to decide the route action. For example, mocking
/// all requests that contain some post data, and leaving all other requests as is:
/// </para>
/// <para>
/// Page routes (set up with <see cref="IPage.RouteAsync"/>) take precedence over browser
/// context routes when request matches both handlers.
/// </para>
/// <para>To remove a route with its handler you can use <see cref="IBrowserContext.UnrouteAsync"/>.</para>
/// </summary>
/// <remarks><para>Enabling routing disables http cache.</para></remarks>
/// <param name="urlString">
/// A glob pattern, regex pattern or predicate receiving <see cref="URL"/> to match
/// while routing.
/// </param>
/// <param name="handler">handler function to route the request.</param>
Task RouteAsync(string urlString, Action<IRoute> handler);

/// <summary>
/// <para>
/// Routing provides the capability to modify network requests that are made by any
/// page in the browser context. Once route is enabled, every request matching the url
/// pattern will stall unless it's continued, fulfilled or aborted.
/// </para>
/// <para>An example of a naive handler that aborts all image requests:</para>
/// <para>or the same snippet using a regex pattern instead:</para>
/// <para>
/// It is possible to examine the request to decide the route action. For example, mocking
/// all requests that contain some post data, and leaving all other requests as is:
/// </para>
/// <para>
/// Page routes (set up with <see cref="IPage.RouteAsync"/>) take precedence over browser
/// context routes when request matches both handlers.
/// </para>
/// <para>To remove a route with its handler you can use <see cref="IBrowserContext.UnrouteAsync"/>.</para>
/// </summary>
/// <remarks><para>Enabling routing disables http cache.</para></remarks>
/// <param name="urlRegex">
/// A glob pattern, regex pattern or predicate receiving <see cref="URL"/> to match
/// while routing.
/// </param>
/// <param name="handler">handler function to route the request.</param>
Task RouteAsync(Regex urlRegex, Action<IRoute> handler);

/// <summary>
/// <para>
/// Routing provides the capability to modify network requests that are made by any
/// page in the browser context. Once route is enabled, every request matching the url
/// pattern will stall unless it's continued, fulfilled or aborted.
/// </para>
/// <para>An example of a naive handler that aborts all image requests:</para>
/// <para>or the same snippet using a regex pattern instead:</para>
/// <para>
/// It is possible to examine the request to decide the route action. For example, mocking
/// all requests that contain some post data, and leaving all other requests as is:
/// </para>
/// <para>
/// Page routes (set up with <see cref="IPage.RouteAsync"/>) take precedence over browser
/// context routes when request matches both handlers.
/// </para>
/// <para>To remove a route with its handler you can use <see cref="IBrowserContext.UnrouteAsync"/>.</para>
/// </summary>
/// <remarks><para>Enabling routing disables http cache.</para></remarks>
/// <param name="urlFunc">
/// A glob pattern, regex pattern or predicate receiving <see cref="URL"/> to match
/// while routing.
/// </param>
/// <param name="handler">handler function to route the request.</param>
Task RouteAsync(Func<string, bool> urlFunc, Action<IRoute> handler);
```

### CODE REVIEW

**Comment by kblok** [comment]
A few thoughts:
We could avoid the type prefix in argument names. `Task RouteAsync(Func<string, bool> urlFunc, Action<IRoute> handler)` could be `Task RouteAsync(Func<string, bool> url, Action<IRoute> handler)`. Not strong tho.

I'm strong on this one. If the argument is not required, we should generate an overload **without** the argument, and the rest of the overloads with the argument as required. I got this issue on my PR as well. This is the example.

```cs
Task<IResponse> WaitForNavigationAsync(string urlString = default, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Regex urlRegex = default, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Func<string, bool> urlFunc = default, WaitUntilState waitUntil = default, float? timeout = default);
```

Should be generated as:

```cs
Task<IResponse> WaitForNavigationAsync(WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(string urlString, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Regex urlRegex, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Func<string, bool> urlFunc, WaitUntilState waitUntil = default, float? timeout = default);
```

Why? Because if I call `Page.WaitForNavigationAsync()` I would get an ambiguous call build error.

**Review by kblok — CHANGES_REQUESTED** [review]
A few thoughts:
We could avoid the type prefix in argument names. `Task RouteAsync(Func<string, bool> urlFunc, Action<IRoute> handler)` could be `Task RouteAsync(Func<string, bool> url, Action<IRoute> handler)`. Not strong tho.

I'm strong on this one. If the argument is not required, we should generate an overload **without** the argument, and the rest of the overloads with the argument as required. I got this issue on my PR as well. This is the example.

```cs
Task<IResponse> WaitForNavigationAsync(string urlString = default, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Regex urlRegex = default, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Func<string, bool> urlFunc = default, WaitUntilState waitUntil = default, float? timeout = default);
```

Should be generated as:

```cs
Task<IResponse> WaitForNavigationAsync(WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(string url, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Regex url, WaitUntilState waitUntil = default, float? timeout = default);

Task<IResponse> WaitForNavigationAsync(Func<string, bool> url, WaitUntilState waitUntil = default, float? timeout = default);
```

Why? Because if I call `Page.WaitForNavigationAsync()` I would get an ambiguous call build error.

**Comment by avodovnik** [comment]
> We could avoid the type prefix in argument names. 

I don't know, it's three different methods, the suffix doesn't hurt. It's just cosmetic so I'd keep it as it is. 

As for the optional one, sure, that makes sense. I'll add it.

**Comment by kblok** [comment]
@avodovnik FYI, I already the changes made in our classes locally. So it would be a matter of getting this merged.

**Comment by avodovnik** [comment]
@kblok this is what we get for `WaitForNavigationAsync`:

```csharp
/// <summary>
        /// <para>
        /// Waits for the main frame navigation and returns the main resource response. In case
        /// of multiple redirects, the navigation will resolve with the response of the last
        /// redirect. In case of navigation to a different anchor or navigation due to History
        /// API usage, the navigation will resolve with <c>null</c>.
        /// </para>
        /// <para>
        /// This resolves when the page navigates to a new URL or reloads. It is useful for
        /// when you run code which will indirectly cause the page to navigate. e.g. The click
        /// target has an <c>onclick</c> handler that triggers navigation from a <c>setTimeout</c>.
        /// Consider this example:
        /// </para>
        /// <para>Shortcut for main frame's <see cref="IFrame.WaitForNavigationAsync"/>.</para>
        /// </summary>
        /// <remarks>
        /// <para>
        /// Usage of the <a href="https://developer.mozilla.org/en-US/docs/Web/API/History_API">History
        /// API</a> to change the URL is considered a navigation.
        /// </para>
        /// </remarks>
        /// <param name="urlString">
        /// A glob pattern, regex pattern or predicate receiving <see cref="URL"/> to match
        /// while waiting for the navigation.
        /// </param>
        /// <param name="waitUntil">
        /// When to consider operation succeeded, defaults to <c>load</c>. Events can be either:
        /// <list type="bullet">
        /// <item><description>
        /// <c>'domcontentloaded'</c> - consider operation to be finished when the <c>DOMContentLoaded</c>
        /// event is fired.
        /// </description></item>
        /// <item><description>
        /// <c>'load'</c> - consider operation to be finished when the <c>load</c> event is
        /// fired.
        /// </description></item>
        /// <item><description>
        /// <c>'networkidle'</c> - consider operation to be finished when there are no network
        /// connections for at least <c>500</c> ms.
        /// </description></item>
        /// </list>
        /// </param>
        /// <param name="timeout">
        /// Maximum operation time in milliseconds, defaults to 30 seconds, pass <c>0</c> to
        /// disable timeout. The default value can be changed by using the <see cref="IBrowserContext.SetDefaultNavigationTimeout"/>,
        /// <see cref="IBrowserContext.SetDefaultTimeout"/>, <see cref="IPage.SetDefaultNavigationTimeout"/>
        /// or <see cref="IPage.SetDefaultTimeout"/> methods.
        /// </param>
        Task<IResponse> WaitForNavigationAsync(string urlString, WaitUntilState waitUntil = default, float? timeout = default);

        /// <summary>
        /// <para>
        /// Waits for the main frame navigation and returns the main resource response. In case
        /// of multiple redirects, the navigation will resolve with the response of the last
        /// redirect. In case of navigation to a different anchor or navigation due to History
        /// API usage, the navigation will resolve with <c>null</c>.
        /// </para>
        /// <para>
        /// This resolves when the page navigates to a new URL or reloads. It is useful for
        /// when you run code which will indirectly cause the page to navigate. e.g. The click
        /// target has an <c>onclick</c> handler that triggers navigation from a <c>setTimeout</c>.
        /// Consider this example:
        /// </para>
        /// <para>Shortcut for main frame's <see cref="IFrame.WaitForNavigationAsync"/>.</para>
        /// </summary>
        /// <remarks>
        /// <para>
        /// Usage of the <a href="https://developer.mozilla.org/en-US/docs/Web/API/History_API">History
        /// API</a> to change the URL is considered a navigation.
        /// </para>
        /// </remarks>
        /// <param name="urlRegex">
        /// A glob pattern, regex pattern or predicate receiving <see cref="URL"/> to match
        /// while waiting for the navigation.
        /// </param>
        /// <param name="waitUntil">
        /// When to consider operation succeeded, defaults to <c>load</c>. Events can be either:
        /// <list type="bullet">
        /// <item><description>
        /// <c>'domcontentloaded'</c> - consider operation to be finished when the <c>DOMContentLoaded</c>
        /// event is fired.
        /// </description></item>
        /// <item><description>
        /// <c>'load'</c> - consider operation to be finished when the <c>load</c> event is
        /// fired.
        /// </description></item>
        /// <item><description>
        /// <c>'networkidle'</c> - consider operation to be finished when there are no network
        /// connections for at least <c>500</c> ms.
        /// </description></item>
        /// </list>
        /// </param>
        /// <param name="timeout">
        /// Maximum operation time in milliseconds, defaults to 30 seconds, pass <c>0</c> to
        /// disable timeout. The default value can be changed by using the <see cref="IBrowserContext.SetDefaultNavigationTimeout"/>,
        /// <see cref="IBrowserContext.SetDefaultTimeout"/>, <see cref="IPage.SetDefaultNavigationTimeout"/>
        /// or <see cref="IPage.SetDefaultTimeout"/> methods.
        /// </param>
        Task<IResponse> WaitForNavigationAsync(Regex urlRegex, WaitUntilState waitUntil = default, float? timeout = default);

        /// <summary>
        /// <para>
        /// Waits for the main frame navigation and returns the main resource response. In case
        /// of multiple redirects, the navigation will resolve with the response of the last
        /// redirect. In case of navigation to a different anchor or navigation due to History
        /// API usage, the navigation will resolve with <c>null</c>.
        /// </para>
        /// <para>
        /// This resolves when the page navigates to a new URL or reloads. It is useful for
        /// when you run code which will indirectly cause the page to navigate. e.g. The click
        /// target has an <c>onclick</c> handler that triggers navigation from a <c>setTimeout</c>.
        /// Consider this example:
        /// </para>
        /// <para>Shortcut for main frame's <see cref="IFrame.WaitForNavigationAsync"/>.</para>
        /// </summary>
        /// <remarks>
        /// <para>
        /// Usage of the <a href="https://developer.mozilla.org/en-US/docs/Web/API/History_API">History
        /// API</a> to change the URL is considered a navigation.
        /// </para>
        /// </remarks>
        /// <param name="urlFunc">
        /// A glob pattern, regex pattern or predicate receiving <see cref="URL"/> to match
        /// while waiting for the navigation.
        /// </param>
        /// <param name="waitUntil">
        /// When to consider operation succeeded, defaults to <c>load</c>. Events can be either:
        /// <list type="bullet">
        /// <item><description>
        /// <c>'domcontentloaded'</c> - consider operation to be finished when the <c>DOMContentLoaded</c>
        /// event is fired.
        /// </description></item>
        /// <item><description>
        /// <c>'load'</c> - consider operation to be finished when the <c>load</c> event is
        /// fired.
        /// </description></item>
        /// <item><description>
        /// <c>'networkidle'</c> - consider operation to be finished when there are no network
        /// connections for at least <c>500</c> ms.
        /// </description></item>
        /// </list>
        /// </param>
        /// <param name="timeout">
        /// Maximum operation time in milliseconds, defaults to 30 seconds, pass <c>0</c> to
        /// disable timeout. The default value can be changed by using the <see cref="IBrowserContext.SetDefaultNavigationTimeout"/>,
        /// <see cref="IBrowserContext.SetDefaultTimeout"/>, <see cref="IPage.SetDefaultNavigationTimeout"/>
        /// or <see cref="IPage.SetDefaultTimeout"/> methods.
        /// </param>
        Task<IResponse> WaitForNavigationAsync(Func<string, bool> urlFunc, WaitUntilState waitUntil = default, float? timeout = default);
        /// <summary>
        /// <para>
        /// Waits for the main frame navigation and returns the main resource response. In case
        /// of multiple redirects, the navigation will resolve with the response of the last
        /// redirect. In case of navigation to a different anchor or navigation due to History
        /// API usage, the navigation will resolve with <c>null</c>.
        /// </para>
        /// <para>
        /// This resolves when the page navigates to a new URL or reloads. It is useful for
        /// when you run code which will indirectly cause the page to navigate. e.g. The click
        /// target has an <c>onclick</c> handler that triggers navigation from a <c>setTimeout</c>.
        /// Consider this example:
        /// </para>
        /// <para>Shortcut for main frame's <see cref="IFrame.WaitForNavigationAsync"/>.</para>
        /// </summary>
        /// <remarks>
        /// <para>
        /// Usage of the <a href="https://developer.mozilla.org/en-US/docs/Web/API/History_API">History
        /// API</a> to change the URL is considered a navigation.
        /// </para>
        /// </remarks>
        /// <param name="waitUntil">
        /// When to consider operation succeeded, defaults to <c>load</c>. Events can be either:
        /// <list type="bullet">
        /// <item><description>
        /// <c>'domcontentloaded'</c> - consider operation to be finished when the <c>DOMContentLoaded</c>
        /// event is fired.
        /// </description></item>
        /// <item><description>
        /// <c>'load'</c> - consider operation to be finished when the <c>load</c> event is
        /// fired.
        /// </description></item>
        /// <item><description>
        /// <c>'networkidle'</c> - consider operation to be finished when there are no network
        /// connections for at least <c>500</c> ms.
        /// </description></item>
        /// </list>
        /// </param>
        /// <param name="timeout">
        /// Maximum operation time in milliseconds, defaults to 30 seconds, pass <c>0</c> to
        /// disable timeout. The default value can be changed by using the <see cref="IBrowserContext.SetDefaultNavigationTimeout"/>,
        /// <see cref="IBrowserContext.SetDefaultTimeout"/>, <see cref="IPage.SetDefaultNavigationTimeout"/>
        /// or <see cref="IPage.SetDefaultTimeout"/> methods.
        /// </param>
        Task<IResponse> WaitForNavigationAsync(WaitUntilState waitUntil = default, float? timeout = default);
```

**Review by yury-s — APPROVED** [review]

**Comment by yury-s** [comment]
@kblok are you ok with committing this in its current form?

**Comment by kblok** [comment]
@yury-s yes! I reviewed the resulting PR on Playwright-Sharp :)

**Pull request merged**
