### PR TITLE
Add a way to debug browser logs

### PR DESCRIPTION
**Pull request by Andarist**
This would be immensely useful for debugging purposes

### CODE REVIEW

**Comment by pavelfeldman** [comment]
Could you explain which messages you are currently missing with the DEBUG=pw:browser today?

**Comment by Andarist** [comment]
We are configuring Playwright to use our fork of Chromium at https://www.replay.io/ . At times, it's helpful for us to debug things happening there using its verbose stdout/stderr output. We can pass the required `RECORD_REPLAY_VERBOSE` env variable to it using `launchOptions` but we still miss the logs because the browser's output is not observable without this added `debug` call

**Comment by pavelfeldman** [comment]
> Could you explain which messages you are currently missing with the DEBUG=pw:browser today?

^^

**Comment by pavelfeldman** [comment]
I.e. if you run DEBUG=pw:browser npx playwright test, what kind of output does not end up printed?

**Comment by pavelfeldman** [comment]
Let's follow the process and file an issue so that we could triage it!

**Pull request closed without merging**
