### PR TITLE
fix(api): split waitForSelectorMissing from waitForSelector

### PR DESCRIPTION
**Pull request by dgozman**
This also drops the notion of visibility, which is pretty vague.

### CODE REVIEW

**Comment by pavelfeldman** [comment]
What was wrong with waiting for various fine-grained events in $wait aka waitForSelector?

**Comment by dgozman** [comment]
> What was wrong with waiting for various fine-grained events in $wait aka waitForSelector?

'visible' / 'hidden' are not strongly defined, and users are confused as of what that means. Now that we don't need 'visible' for click and friends, we can provide more predictable semantics:

```
const e = await page.waitForSelector('foo');  // waits for element to exist
await e.click();  // waits for element to be clickable.
```

This way we avoid mismatch between what playwright means by 'visible', and what user thinks about it. I can leave `{ missing: true }` option, but it seems like separate method is easier to find/understand.

**Comment by dgozman** [comment]
> What was wrong with waiting for various fine-grained events in $wait aka waitForSelector?

'visible' / 'hidden' are not strongly defined, and users are confused as of what that means. Now that we don't need 'visible' for click and friends, we can provide more predictable semantics:

```
const e = await page.waitForSelector('foo');  // waits for element to exist
await e.click();  // waits for element to be clickable.
```

This way we avoid mismatch between what playwright means by 'visible', and what user thinks about it. I can leave `{ missing: true }` option, but it seems like separate method is easier to find/understand.

**Comment by pavelfeldman** [comment]
I already did not like the `waitForSelector` name - it should be `waitForElement` or just `$wait` :-). I'd say this is a rare case, so no need for a separate method. It could easily be `page.$wait('button', { gone: true })`. We can scale `$wait` with more options and that is handy...

**Pull request closed without merging**
