### PR TITLE
feat: Add `timeoutMessage` option to launch and interaction methods

### LINKED ISSUE #4665: [Feature] Add custom failure message to `waitForSelector` method
Currently when timeout happens the following error is thrown
```
        TimeoutError {
          message: `page.waitForSelector: Timeout 30000ms exceeded.
          =========================== logs ===========================
          waiting for selector "//th[@class="hds-table-column-sorting"][1]" to be visible
          ============================================================
          Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.`,
        }
```

It would be very useful on report analysis to have something like 

```typescript
page.waitForSelector('img', {message: 'My important image did not appear' })
```

And as result to get
```
        TimeoutError {
          message: `page.waitForSelector: Timeout 30000ms exceeded.
          =========================== logs ===========================
          My important image did not appear
          ============================================================
          Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.`,
        }
```
And if message is not provided - then display the way it is now.

### PR DESCRIPTION
**Pull request by tymfear**
Closes #4665.

### CODE REVIEW

**Comment by tymfear** [comment]
Hi! Originally wanted the `waitForSelector` option to have a custom error message, but while working on that realized, that it would be beneficial to have that kind of option for any method that throws `TimeoutError`. Tried to figure out all the places, but could miss something. There is a lot of changes and naming might be not that great, but let's start with something!

**Comment by JoelEinbinder** [comment]
Thanks for the PR! Sorry that we have been a bit slow with reviews over the holidays.

I'm finding this feature a bit strange. You get a stack trace for the timeout right? Why can't you just put a comment on that line with your message?

**Comment by tymfear** [comment]
@JoelEinbinder the thing is that this feature not for people who read the code, but for those who analyze logs.
You definitely can put a comment (which is unnecessary in most of the cases if your code is self-descriptive), but that will not solve the issue here:
```
        TimeoutError {
          message: `page.waitForSelector: Timeout 30000ms exceeded.
          =========================== logs ===========================
          waiting for selector "//th[@class="hds-table-column-sorting"][1]" to be visible
          ============================================================
          Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.`,
        }
```

This message does not explain what is exactly wrong and what is that element to those, who do not contribute to test harness often. Even if you have a screenshot, it's not always obvious which element did not appear or changed selector.
So with proposed changes it would be something like
```
        TimeoutError {
          message: `page.waitForSelector: Timeout 30000ms exceeded. Sorting did not appear for column "Name".
          =========================== logs ===========================
          waiting for selector "//th[@class="hds-table-column-sorting"][1]" to be visible
          ============================================================
          Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.`,
        }
```

The same feature is available for Selenium (which basically where I got the idea, since I use this feature quite heavily.)
https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_WebDriver.html#wait

**Comment by JoelEinbinder** [comment]
The timeout error should contain a stack trace. If it doesn't that's a bug we should definitely fix. Once there is a stack trace, most test runners will dump the line from your test into the logs. That will contain the comment on the line, if any.

**Comment by tymfear** [comment]
@JoelEinbinder probably I don't understand what you mean by comment. So here is a code example
```javascript
const { chromium } = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  try {
    // comment above the line
    await page.waitForSelector('some dumb selector', { timeout: 1 }); // comment on the line
  } finally {
    await page.close();
    await browser.close();
  }
})();
```

And here is an output of running the script `DEBUG=pw:api node pwTimeoutCheck.js`
```
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +293ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +5ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +215ms
  pw:api => page.waitForSelector started +0ms
  pw:api waiting for selector "some dumb selector" to be visible +4ms
  pw:api <= page.waitForSelector failed +5ms
  pw:api => page.close started +0ms
  pw:api => browserContext.close started +12ms
  pw:api <= browserContext.close succeeded +3ms
  pw:api <= page.close succeeded +0ms
  pw:api => browser.close started +0ms
  pw:api <= browser.close succeeded +43ms
(node:81889) UnhandledPromiseRejectionWarning: page.waitForSelector: Timeout 1ms exceeded.
=========================== logs ===========================
waiting for selector "some dumb selector" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/channelOwner.js:44:61)
    at /Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/frame.js:180:48
    at Frame._wrapApiCall (/Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/channelOwner.js:72:34)
    at Frame.waitForSelector (/Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/frame.js:175:21)
    at /Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/page.js:212:60
    at Page._attributeToPage (/Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/page.js:202:20)
    at Page.waitForSelector (/Users/daudty/projects/forks/devices-webapp/node_modules/playwright-chromium/lib/client/page.js:212:21)
    at /Users/daudty/projects/forks/devices-webapp/pwTimeoutCheck.js:8:16
```

Could you clarify, please?

**Comment by JoelEinbinder** [comment]
You can `try-catch` the timeout error and append a message to it if you are using a page object. It doesn't seem like this feature adds a lot of value, and it would take up a lot of api surface area. Maybe I just don't get it though, I'll let somebody else on the team take a look.

**Comment by tymfear** [comment]
@JoelEinbinder what you suggest is to wrap every call in it's own try/catch block, or add catch clause on every element location/awaiting - this is super inconvenient.   
But this is extremely valuable feature, even if does not seem like that, when you build massive test harness with hundreds/thousands of tests. 

I worked in companies where manual QAs were analysing test reports - so they very much appreciated more descriptive error messages, than just some css/xpath selector (some of them even didn't know what is css/xpath selector).

I could share company process examples that would greatly benefit from that kind of feature.

TBH, I was very surprised that this feature is not available out of the box.

**Comment by JoelEinbinder** [comment]
That's certainly a lot to think about. We have a similar problem with our own code, and we solve it by recording the steps leading up to the timeout. Maybe users would want to do something like that instead of annotating every possible error location. Like I said, I'll talk about it with the team. Things are a little slow because of the holidays.

In the meantime I wrote you a helper method you can use in your tests.

```js
/**
 * @template T
 * @param {string} message 
 * @param {Promise<T>} promise
 * @return {Promise<T>}
 */
function timeoutMessage(message, promise) {
  return promise.catch(e => {
    if (e instanceof require('playwright').errors.TimeoutError)
      e.message += '\n' + message;
    throw e; 
  });
}
// ...
await timeoutMessage('oops it timed out', page.waitForSelector('hello'));
```

**Comment by tymfear** [comment]
@JoelEinbinder - so any update on this? Having this kind of error is very annoying, because developers don't want to figure out what is broken by the selector and this feature would remove that annoying part in test results analysis. 
I understand that code is super outdated now when 2 months have passed, but don't want to waste more time on this if you refuse to take it in anyway.

**Comment by mxschmitt** [comment]
Closed since it seemed stale, for now this should be implemented from the user-land. Also test-runners should report this error with a direct location to the line which threw it when the test-runner timeout is > the playwright deadline.

**Pull request closed without merging**
