### PR TITLE
[docs] update import in code example

### PR DESCRIPTION
**Pull request by rubenhelsloot**

### CODE REVIEW

**Comment by pavelfeldman** [comment]
As seen from the bots, you did not run the generators that modify docs in the source.

**Review by mxschmitt — APPROVED** [review]

**Comment by mxschmitt** [comment]
@rubenhelsloot do you mind signing the [CLA](https://github.com/microsoft/contributorlicenseagreement) for us?

**Comment by mxschmitt** [comment]
@rubenhelsloot do you mind signing the [CLA](https://github.com/microsoft/contributorlicenseagreement) for us?

**Comment by rubenhelsloot** [comment]
@microsoft-github-policy-service agree [company="Pieter Pot"]

**Comment by rubenhelsloot** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
