### PR TITLE
chore: remove toIntersectViewport for the next release

### PR DESCRIPTION
**Pull request by dgozman**
Mostly reverts #19901.

### CODE REVIEW

**Review by pavelfeldman — APPROVED** [review]

**Comment by arieluchka-bse** [comment]
hi, why was this feature reverted?
is there an alternative to assert that an element shows fully in viewport?

**Comment by mxschmitt** [comment]
Its called nowadays [`toBeInViewport()`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-in-viewport)

**Comment by arieluchka-bse** [comment]
> Its called nowadays [`toBeInViewport()`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-in-viewport)

wasnt toIntersectViewport meant to validate chunks of the element? that the whole element is in the viewport and not only half of it?

i saw that the [toBeInViewport()](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-in-viewport) has "ratio" attribute, but it doesn't seem to work for me, so i wonder if im just using the wrong method, or is it just not compatible with our ui (angular, i think).


we have an element that on different viewports, half of it will collapse. 
i am trying to write a test to validate the whole element is visible on different viewports.


image
vs
image

**Comment by mxschmitt** [comment]
Please file a new issue, thats a better point to triage bug reports. Thank you.

**Comment by arieluchka-bse** [comment]
should i open in [playwrights repo](https://github.com/microsoft/playwright) or [pythons playwright repo](https://github.com/microsoft/playwright-python)?
thank you for the help :)

**Comment by mxschmitt** [comment]
https://github.com/microsoft/playwright/

**Pull request merged**
