### PR TITLE
docs(selectors.md): React selector nit

### PR DESCRIPTION
**Pull request by rwoll**
See https://github.com/microsoft/playwright/pull/11970#discussion_r803212908.

In the future, I'd like to think through some more extensive examples to make React selector best practices more explicit in the docs.

### CODE REVIEW

**Comment by rwoll** [comment]
cc: @aslushnikov for review

**Review by aslushnikov — APPROVED** [review]

**Comment by sksk013djjdjx-commits** [comment]
+1 (289) 989-1658

**Comment by sksk013djjdjx-commits** [comment]
+1 (289) 989-1658 for assignee

**Comment by sksk013djjdjx-commits** [comment]
+1 (289) 989-1658

**Comment by sksk013djjdjx-commits** [comment]
+880 1917-248317

**Comment by sksk013djjdjx-commits** [comment]
+880 1917-248317

**Comment by sksk013djjdjx-commits** [comment]
+880 1917-248317

**Pull request merged**
