### PR TITLE
Add sudo package to Docker image

### PR DESCRIPTION
**Pull request by Niek**
This change adds the git package to the Dockerfile. Without it, it's not possible to install NPM packages from git (`npm i user/repo#master`) which is quite useful.

### CODE REVIEW

**Comment by mxschmitt** [comment]
> This change adds the git package to the Dockerfile. Without it, it's not possible to install NPM packages from git (`npm i user/repo#master`) which is quite useful.

Hey, thank you for your contribution!

In the NPM world, I would say its quite rare that packages will be installed directly from a Git server. I would leave it out to the user, who needs it, instead installing it in the official Docker image for everyone to save bandwidth.

**Comment by Niek** [comment]
I see, what makes it a bit complicated is that the Dockerfile doesn't include sudo either, so it's not possible to installs additional packages from the `pwuser` account. What about this change (see new commit)?

**Comment by yury-s** [comment]
This sounds specific to the scenario where you want to install from git and not required in the common case when everything is installed via npm. It can be easily achieved by  installing sudo, git and other extras on top of the base image we provide. Also granting `pwuser` root access, especially without password, is a security risk.

**Comment by Niek** [comment]
As said it's not really possible to install extra packages, unless I start the image with `-u root` and manually su to pwuser afterwards. But I understand that's desired behavior, so I'll close this PR.

**Pull request closed without merging**
