### PR TITLE
Multiple large files test

### PR DESCRIPTION
**Pull request by kurilov**

### CODE REVIEW

**Comment by kurilov** [comment]
@microsoft-github-policy-service agree

**Comment by dgozman** [comment]
@kurilov Is this related to some bug? Could you please file an issue first?

**Comment by kurilov** [comment]
> @kurilov Is this related to some bug? Could you please file an issue first?

@dgozman  i made an issue

**Comment by kurilov** [comment]
Fixed in https://github.com/microsoft/playwright/issues/23258

**Pull request closed without merging**
