### PR TITLE
feat(ui): highlight output toggle button if terminal contains error

### LINKED ISSUE #32368: [Bug]: Low discoverability of `webServer` errors in UI Mode Output
### Version

1.46.1

### Steps to reproduce

1. Configure `webServer[0].command` to something that will throw an error (eg. `exit 1` or something more realistic like the reproduction link below)
2. Observe that there is no feedback in either the UI or in the terminal that anything has gone wrong, but all tests are missing ("No tests" message) and "No errors" in the Errors tab, see screenshot below

356570173-3079baa1-db06-4e2c-934d-aafaa6503676

Since @pavelfeldman's PR https://github.com/microsoft/playwright/pull/31824, there is a separate tab which shows the `stdout` and `stderr`, but [this is pretty hidden](https://github.com/microsoft/playwright/issues/31300#issuecomment-2277726618) - multiple users reported that it's hard to find, in that issue and offline

### Reproduction Repo

Reproduction: https://github.com/karlhorky/repro-playwright-ui-mode-missing-stderr-stdout

### Expected behavior

When a `webServer` process exits with a non-zero exit code, Playwright UI Mode switches automatically to the "Output" tab to show the error

### Actual behavior

When a `webServer` process exits with a non-zero exit code, no feedback is shown to the user, and "No tests" appears

It's up to the user to find out that there is [a hidden "Output" tab](https://github.com/microsoft/playwright/issues/31300#issuecomment-2277726618) which shows the errors

### Additional context

Originally, there was no way to see the `stdout` and `stderr` of the web servers:

- https://github.com/microsoft/playwright/issues/31300

But `stdout` and `stderr` are shown in the output panel in `1.46.0` after this PR:

- https://github.com/microsoft/playwright/pull/31824

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 38.27 MB / 16.00 GB
  Binaries:
    Node: 20.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
    bun: 1.1.25 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.92.2 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
```

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/microsoft/playwright/issues/32368

Screenshot 2024-08-30 at 13 22 39

### CODE REVIEW

**Comment by karlhorky** [comment]
The red outline ironically makes it less noticeable to my eye.

@skn0tt what do you think about a red dot at the top right of the icon instead? Eg. something like:

Screenshot 2024-08-30 at 14 50 56

That may be more visually noticeable...

**Comment by pavelfeldman** [comment]
The patch looks good.

> @Skn0tt what do you think about a red dot at the top right of the icon instead? Eg. something like this red dot (ignore the inbox icon, unrelated):

I second this, but with a different rationale. We should make sure UI is accessible and your change communicates erroneous state in a way color blindness does not allow to register.

**Comment by Skn0tt** [comment]
Sounds good! Honestly, I think I was just being lazy. Looks like i'm gonna need to pull out my CSS skills.

**Comment by Skn0tt** [comment]
Here's how it looks now:

Screenshot 2024-09-10 at 11 11 48

**Comment by Skn0tt** [comment]
@pavelfeldman could you take another look?

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
