### PR TITLE
browser(webkit): wait for parsing before emitting Page.frameStoppedLoading

### PR DESCRIPTION
**Pull request by JoelEinbinder**
The code here is very complicated, but experimentally this line works.

Maybe this can get upstreamed and somebody from the webkit team can take a look? There is some accessibility
code running with the progress controller so I think it could be a real bug.

References #8340﻿

### CODE REVIEW

**Comment by pavelfeldman** [comment]
That's pretty random, I'm sure you are breaking the browser.

**Comment by JoelEinbinder** [comment]
> That's pretty random, I'm sure you are breaking the browser.

I'm not sure what to do with this comment.

**Comment by canonic-epicure** [comment]
You could also just manually wait for the `document.readyState` property to have a required value?

**Comment by canonic-epicure** [comment]
@JoelEinbinder A friendly bump for this PR, because it seems to be stalled and I'm interested in the original issue to be fixed.

Could it be fixed in the "user land" instead of "C++ land"? One can manually wait for the `document.readyState` to have correct value? This can be applied only for Webkit.

**Comment by dgozman** [comment]
We discussed this one, and the way forward is to avoid using `Page.frameStoppedLoading` signal. @joeleinbinder suggests that we'll need a separate signal for `window.stop()` handling which is ok.

**Pull request closed without merging**
