### PR TITLE
docs(python): fix set_viewport_size in emulation.md

### LINKED ISSUE #1166: [BUG] Inconsistent documentation for page.set_viewport_size()
**Context:**
* https://playwright.dev/python/docs/emulation#viewport
* https://playwright.dev/python/docs/api/class-page#page-set-viewport-size

**Describe the bug**

[emulation#viewport](https://playwright.dev/python/docs/emulation#viewport) describes `page.set_viewport_size(height:int, width:int)`, while the method is [documented itself](https://playwright.dev/python/docs/api/class-page#page-set-viewport-size) as `page.set_viewport_size(size:dict[height:int, width:int])`, while the description itself also mentions `page.setViewportSize()`.

I think it makes a lot of sense (and would be intuitive) to allow  `page.set_viewport_size(height:int, width:int)` in addition to the backwards compatible (but rather js centric) `page.set_viewport_size(size:dict[height:int, width:int])`. But in any case, the docs being inconsistent is rather annoying. :-)

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/microsoft/playwright-python/issues/1166

### CODE REVIEW

**Comment by dwt** [comment]
This misses the typo at https://playwright.dev/python/docs/api/class-page#page-set-viewport-size where the docs talk about `page.setViewportSize` instead of `page.set_viewport_size`

**Comment by dwt** [comment]
Are you guys considering also allowing the more pythonic `page.set_viewport_size(height:int, width:int)` as an alternative or is that out because of backwards compatibility?

**Comment by mxschmitt** [comment]
> 

There is no plan to also allow it, it's the `dict` variant for now. It was only different before 1.x of Playwright for Python.

**Comment by dwt** [comment]
With that: lgtm for what it's worth.

**Review by aslushnikov — APPROVED** [review]

**Pull request merged**
