### PR TITLE
feat(api): add method to `setDefaultTimeout` for browser

### LINKED ISSUE #5495: [Feature] Global or browser timeout
There is setDefaultTimeout for browserContext and for page but not for the browser. Maybe I missed something but it would be really nice to have a global or browser based timeout.

### PR DESCRIPTION
**Pull request by anirudh-modi**
Closes #5495 

## Todo
- [x] Add `setDefaultTimeout` for browser
- [x] Add new base test case for fallback to browser level timeout
- [x] Update docs for support of `setDefaultTimeout` for browser

### CODE REVIEW

**Comment by anirudh-modi** [comment]
Hi @dgozman @aslushnikov based on the requirement mentioned in the issue, I felt these changes should be done.. 

I have also added a test case.. but, do I need to separately add a new test case for multiple `browserContext`?

Please, let me know if any more changes are required or not.

**Comment by anirudh-modi** [comment]
Any feedback on this PR..

**Comment by aslushnikov** [comment]
Hey @anirudh-modi, thank you for the awesome patch!

And while the code itself looks good, we do have some strategic concerns here that I posted [here in the issue discussion](https://github.com/microsoft/playwright/issues/5495#issuecomment-873203684), so I'd love to hold from landing this. At the very least until there are more use cases in the issue and more interested clients in this API to justify the change.

**Comment by anirudh-modi** [comment]
Hi @aslushnikov No worries... I understand about the same..

Can you guide me with one thing, about what is the pattern which the team follows when it comes to picking and resolving issues? 

I am looking to forward to be contribute to playwright.. so I am slowly trying to expand my comfort zone and increasing my familiarity with the codebase..

This maybe helpful for me to contribute meaningfully

**Comment by anirudh-modi** [comment]
Because, if I randomly pick things up, I am sure that would disrupt the flow of the entire team.. 

as perhaps this may have done.. so I want to ensure that perhaps I am contributing in right direction without being overhead for the team..

**Comment by aslushnikov** [comment]
@anirudh-modi the best way is to head over to the #contributors channel on https://aka.ms/playwright-slack and ask there!

**Pull request closed without merging**
