### PR TITLE
fix(firefox): disable ICC color correction based on OS display

### PR DESCRIPTION
**Pull request by dgozman**

### CODE REVIEW

**Review by aslushnikov — APPROVED** [review]
Awesome!

**Comment by JoelEinbinder** [comment]
Nice!

**Comment by JoelEinbinder** [comment]
This is great, and we should land it, but in theory it would be nice to have color correction only off of screenshots.

**Comment by aslushnikov** [comment]
> This is great, and we should land it, but in theory it would be nice to have color correction only off of screenshots.

I wouldn't bother for now - we were messing with Chromium colors (`--force-color-profile`) for a while and to the best of my knowledge it didn't hurt folks.

**Pull request merged**
