### PR TITLE
feat(inspector): add keyboard shortcuts (#12014)

### LINKED ISSUE #12014: [Feature] Keyboard shortcuts in inspector
### Discussed in https://github.com/microsoft/playwright/discussions/11891

<div type='discussions-op-text'>

<sup>Originally posted by **huy-nguyen** February  6, 2022</sup>
Is it possible to add keyboard shortcuts for debugging functionality in the inspector in a similar manner to Chrome dev tools, for example, F8 for run, F10 for step over etc?</div>

### PR DESCRIPTION
**Pull request by jfgreffier**
My first PR 🙂
Fixes #12014
Adds keyboard shortcuts in inspector : F8 to run/pause, F10 to step over.

### CODE REVIEW

**Comment by Meir017** [comment]
@jfgreffier consider adding docs in https://github.com/microsoft/playwright/blob/main/docs/src/inspector.md

**Comment by jfgreffier** [comment]
Done. Thanks for the suggestion.

**Comment by Meir017** [comment]
@jfgreffier sorry for not mentioning this before, I think tests should be added here https://github.com/microsoft/playwright/blob/main/tests/library/inspector/pause.spec.ts 

similar to this - https://github.com/microsoft/playwright/blob/71dcad3b2e03231a4f88d58e397e69417254888a/tests/library/inspector/pause.spec.ts#L47-L54

**Comment by jfgreffier** [comment]
My bad. Tests in a separate folder as inspector and not recorder made me think there were none (!).

I've fixed selectors in tests that were based on `title`, and added tests cases.

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
