### PR TITLE
Revert "feat: introduce touchscreen.touch() for dispatching raw touch…

### PR DESCRIPTION
**Pull request by yury-s**
… events (#31457)"

This reverts commit a3e31fd2c4146e67a63ff4d3dc4f655533adcbde.

### CODE REVIEW

**Review by mxschmitt — APPROVED** [review]

**Comment by wangdatu** [comment]
Why did you restore touchscreen. touch()? Is there any other way to replace Touchstart、 touchmove、touchend

**Comment by ml4725** [comment]
+1

**Comment by ml4725** [comment]
This feature is very useful. What was the reason for its cancellation? Will it be reinstated in the future?

**Comment by wangdatu** [comment]
> +1

Hello, may I ask how you are currently implementing touchstart, touchmove, and touchend actions?

**Comment by Hacktivist668** [comment]
Is there still hope for this feature to be supported?

**Comment by tphillips-ict** [comment]
> This feature is very useful. What was the reason for its cancellation? Will it be reinstated in the future?

Interesting that there wasn't much communication around this, but looking at the code this feature was incomplete (e.g. it wasn't yet supported for Firefox). Maybe work was started on it but the team decided something else was higher priority?

**Pull request merged**
