### PR TITLE
fix(recorder): Fix recorder out of view

### LINKED ISSUE #5696: [BUG] Playwright Inspector window is opened outside of visible screen
**Context:**
- Playwright Version: 1.9.0
- Operating System: Windows10 
- Node.js version: v12.18.2
- Browser: Chromium 
- Extra: laptop with 13,3" screen, 1920 x 1080 (FullHD) resolution, scaled to 150%, setup with external monitor placed above laptop screen

Example script 
```javascript
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
})().then(() => console.log('finished'));
```

When trying to debug script (set PWDEBUG=1) Playwright Inspector window is opened by Playwright outside of visible screen space - it is opened past the right border of the screen.

in 
src\server\supplements\recorder\recorderApp.ts RecorderApp.open
there is a definitions of arguments for opening the window
const args = [
      '--app=data:text/html,',
      '--window-size=600,600',
      '--window-position=1280,10',
    ];
when 1280 is changed to say 700 then Playwright Inspector windows is visible after it is first opened by Playwright.

### PR DESCRIPTION
**Pull request by kumaraditya303**
Fixes https://github.com/microsoft/playwright/issues/5696

### CODE REVIEW

**Comment by pavelfeldman** [comment]
This is hardly a fix, you fix those with logical screens < 1280, but regress experience for everyone.

**Comment by kumaraditya303** [comment]
Even in trace viewer the window position is not set and it works fine  https://github.com/microsoft/playwright/blob/f40611306e950bf18071c5c4d810510d90fd5937/src/server/trace/viewer/traceViewer.ts#L132

**Comment by pavelfeldman** [comment]
It'll be showing on top of the target window, which would be a major annoyance...

**Comment by kumaraditya303** [comment]
> It'll be showing on top of the target window, which would be a major annoyance...

Currently on windows it is just not visible, with this patch it shows, do you have any other fix for this else I think something is better than nothing

**Comment by mxschmitt** [comment]
Seems stale, closing as part of the triage process.

**Pull request closed without merging**
