### PR TITLE
test: add REPORT_ONLY mode for test collection

### PR DESCRIPTION
**Pull request by dgozman**

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
This wouldn't work for an external user who uses one of the globals we don't override. Like test or todo. I don't know what the requirements are for this code though.

@pavelfeldman ptal

**Comment by dgozman** [comment]
> This wouldn't work for an external user who uses one of the globals we don't override. Like test or todo. I don't know what the requirements are for this code though.
> 
> @pavelfeldman ptal

Oh, this is for our internal test collection and reporting. It only makes sense together with skip/fail, so we wouldn't bring this to external users unless we bring skip/fail.

**Review by pavelfeldman — COMMENTED** [review]
Why not to make the test function noop? Would be a single line change or what do I miss?

**Comment by dgozman** [comment]
> Why not to make the test function noop? Would be a single line change or what do I miss?

This is what I do, but we also need to collect the skip/fail status.

**Comment by dgozman** [comment]
Please take another look, I've simplified things a bit.

**Review by pavelfeldman — APPROVED** [review]
That's what I meant!

**Pull request merged**
