### PR TITLE
chore: update CDN endpoints

### PR DESCRIPTION
**Pull request by mxschmitt**

### CODE REVIEW

**Review by Skn0tt — APPROVED** [review]
looks good!

**Review by agg23 — APPROVED** [review]

**Review by pavelfeldman — APPROVED** [review]

**Comment by jamietanna** [comment]
Just to confirm, is there anything as a user that's needed to respond to this + the decommissioning of the CDNs, i.e. wait for the next release, as it looks like [the current release only uses the `azureedge.net` CDN endpoints](https://github.com/microsoft/playwright/blob/v1.49.1/packages/playwright-core/src/server/registry/index.ts#L39-L43)?

**Comment by Skn0tt** [comment]
We still control the domains and they point to a different CDN now that's managed by us. No user change needed.

**Comment by jamietanna** [comment]
Good to know, thank you! So to confirm - in this specific case - we could happily continue to use an older version of Playwright which points to `playwright.azureedge.net` and won't see any impact related to [the retirement of the azureedge.net CDN](https://build5nines.com/retirement-of-azureedge-net-dns-edg-io-business-closure-and-what-you-need-to-know/)?

**Comment by Skn0tt** [comment]
Correct! Also, based on my understanding of this deprecation, its' not `azureedge.net` that's being deprecated, but only the Edg.io-powered CDNs that were hosted there. That impacts the `playwright-akamai.azureedge.net` and `playwright-verizon.azureedge.net` domains (ignore the naming, both were on Edg.io), but it doesn't impact the `playwright.azureedge.net` domain - that points to Azure Frontdoor, which isn't going away. So you're double-safe!

**Comment by jamietanna** [comment]
Interesting, thanks for the reply!

My reading of [FAQ: Can I retain my existing `*.azureedge.net` domain when I move to Azure Front Door?](https://learn.microsoft.com/en-us/azure/cdn/edgio-retirement-faq#can-i-retain-my-existing-azureedgenet-domain-when-i-move-to-azure-front-door) is that external parties (i.e. folks using an older version of Playwright) shouldn't still have any references to the `.azureedge.net` domains:

> Relying on domains like `*.azureedge.net` and `*.azurefd.net` isn't recommended as it poses availability risks.

Via [Retirement of AzureEdge.net DNS: Edg.io Business Closure and What You Need to Know](https://build5nines.com/retirement-of-azureedge-net-dns-edg-io-business-closure-and-what-you-need-to-know/):

> Microsoft has announced the retirement of the azureedge.net domain by January 15, 2025

This - to me - reads as _the whole domain should / will no longer be usable_ after this date, so any existing usages of that domain will i.e. result in 404s/DNS lookup failures.

Appreciate that I've only just heard about this and am responding (as well as being somewhat unfamiliar with Azure's offerings), so may have missed some of the nuance here, and am happy to follow your commentary with the fact that it'll be OK to continue being on versions of Playwright that reference `*.azureedge.net`, past 2025-01-15

**Comment by Skn0tt** [comment]
> Relying on domains like *.azureedge.net and *.azurefd.net isn't recommended as it poses availability risks.

Absolutely correct, we failed at this in the past. We're moving to `cdn.playwright.dev` to remove this risk in the future.

> Microsoft has announced the retirement of the azureedge.net domain by January 15, 2025

I saw that in the build5nines.com article, but it doesn't match the messaging we received from Azure about it. I'm pretty sure the article is incorrect here, as pointed out in my earlier message.

> happy to follow your commentary with the fact that it'll be OK to continue being on versions of Playwright that reference *.azureedge.net, past 2025-01-15

You'll be OK, and we're making sure of that. The Playwright team and @mxschmitt in particular looked very closely into this change and ensured that things will continue to be fine past 01-15. In the unlikely event that things still go bad, we can still publish fixup version for all supported Playwright versions. And for everything else, there's an [environment variable](https://github.com/microsoft/playwright/blob/6bdd2694ee6b0d34bfc8fb4151223c6f3e31a9e5/packages/playwright-core/src/server/registry/index.ts#L1149-L1159) that can be used to change the CDN.

**Comment by jamietanna** [comment]
Thanks very much for the reassurance, it's very appreciated.

I guess that _probably_ also means that there's no wider need to move away from a `azureedge.net` domain? It's more that we should be avoiding / migrating from anything that's on `edg.io`?

**Comment by Skn0tt** [comment]
> I guess that probably also means that there's no wider need to move away from a azureedge.net domain?

That's my understanding, yes - but for your own web properties, don't base your decisions on me. I recommend you follow first party guidelines on that - look at what the Azure CDN team publishes, not what I or a third-party news outlet is saying.

**Comment by shanselman** [comment]
> Thanks very much for the reassurance, it's very appreciated.
> 
> I guess that _probably_ also means that there's no wider need to move away from a `azureedge.net` domain? It's more that we should be avoiding / migrating from anything that's on `edg.io`?

If I had important things on azureedge I would move them. I moved all my personal things, blog, podcast, website, onto custom domains and I would recommend that to everyone.

**Pull request merged**
