### PR TITLE
chore(devops): restructured / added Dockerfiles for Debian and Ubuntu 20

### PR DESCRIPTION
**Pull request by mxschmitt**
I had some modified Dockerfiles lying around on my disk, probably they are useful for others. Changes:
- Grouped APT calls into a single APT call as discussed here: https://github.com/microsoft/playwright/pull/2656#issuecomment-647003569
- Added Ubuntu (20 - focal) - latest LTS release of Ubuntu
- Added Debian (10 - buster) - based on `node:12-buster-slim` a bit more lightweight, different and also common as a Docker base image. Needed also the custom `libjpeg` build, as proposed here: https://github.com/microsoft/playwright/issues/2437#issuecomment-642860416.

With these the users, should be have more official Dockerfiles to get started with Playwright and see easier which dependencies are required in which Linux distribution (rather than just a list of deps in the docs).

Tested all of these three with Try Playwright locally, all of the browsers are working, making screenshots and interaction works.

Follow up questions:
- Maybe replace the `bionic` (Ubuntu 18) build to the `focal` (Ubuntu 20) build everywhere?
- @arjun27 can we push them also to the Docker registry as soon as its merged?

Relates to #3338

### CODE REVIEW

**Comment by arjun27** [comment]
Thanks @mxschmitt! I pushed some docs changes in #2760, and it might be worth rebaselining over it.

I'm personally not sure giving these options. My concern is the maintenance overhead of these variations: we would want to dogfood them on our CI to ensure they keep working. I haven't seen user interest in such flexibility. There has been user interest in docker images that include browser binaries and I think that is a worthy enhancement over what we have. Open to more opinions on this however, I might be missing something.

Adding a Debian variation definitely helps users that are using existing images based on Debian (and cannot switch over to a different image altogether). Adding a reference dockerfile for them makes sense, but we should think about how to dogfood them before merging these – to ensure they don't deteriorate over time. 

cc @aslushnikov

**Comment by mxschmitt** [comment]
Friendly ping @aslushnikov how shall we proceed with that? I see a lack in two topics:
- which dependencies are needed for which browsers (experienced in the Heroku buildpack, that the comments for the browsers are not totally correct. Sometimes browsers need additional/overlapping dependencies).
- which dependencies are needed for major needed linux distributions.
What are your thoughts on that?

**Comment by mxschmitt** [comment]
Since [Python3](https://hub.docker.com/_/python) and [Node.js](https://hub.docker.com/_/node) images are per default based on Debian Buster, this was also my intention to help users with these configuration templates. Maybe soon when we start with Language based images, we can investigate further.

**Comment by xylix** [comment]
I'm a user who needs ubuntu 20.04 for our testing so I actually started to contribute my own variation https://github.com/microsoft/playwright/pull/3338 because I missed that this PR existed. 

If there's no interest in maintaining multiple Dockerfiles for ubuntu I would definitely ask you consider supporting 20.04 since it is now the latest LTS and supported by Playwright as of latest release.

Is there some help you would like with this?

**Comment by nchudleigh** [comment]
@mxschmitt Awesome work here this is really useful for my team.  Wondering if you had success running all browsers in the buster-slim image?

I am still running into missing dependency issues with a few core modules.

**Comment by jaylinski** [comment]
> @mxschmitt Awesome work here this is really useful for my team. Wondering if you had success running all browsers in the buster-slim image?
> 
> I am still running into missing dependency issues with a few core modules.

Even if you install all missing deps, you will still get page crashes in webkit: https://github.com/microsoft/playwright/issues/3167#issuecomment-671987362 :neutral_face:

**Comment by dgozman** [comment]
@mxschmitt Should we close this PR?

**Comment by mxschmitt** [comment]
> @mxschmitt Should we close this PR?

Yeah, all action items were fixed or extracted into a separate issue and the grouping of apt installs was marked as non-relevant.

WebKit Debian Headless: #3167

**Pull request closed without merging**
