### PR TITLE
feat: introduce ember selector engine

### PR DESCRIPTION
**Pull request by lifeart**
refs: https://github.com/microsoft/playwright/pull/8070/files

Should work for Ember starting from `3.14.0`, debug API introduced in [Debug Render Tree (for Ember Inspector)](https://github.com/emberjs/ember.js/pull/18372)

[How to get it working in prod env
](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/environment/lib/env.ts#L129)
To do:

- [x] Add documentation
- [x] Add engine selector logic
- [x] Add ember app for tests bundle created using this default ember app modifications https://gist.github.com/lifeart/b6df15f7197331314477b4a7a5349d6f
- [x] Add multiapp support 
- [x] Simplify ember components definition for maintainers

This is how `/tests/assets/reading-list/ember3.html` looks in ember-inspector

image

[Ember Inspector Extension](https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi?hl=en)

If Ember Inspector is not working for `file://` url's
* Visit the URL:  `chrome://extensions`.
* Find the Ember Inspector (`chrome://extensions/?id=bmdblncegkenkacieihfhpjfppoconhi`)
* Make sure "Allow access to file URLs" is checked.

### CODE REVIEW

**Comment by aslushnikov** [comment]
Hey @lifeart,

We have no ember experts on the team right now 🤷‍♂️. Could you publish this as a plugin for now? Selector engines could be registered with [`selectors.register`](https://playwright.dev/docs/api/class-selectors#selectors-register) method.

**Comment by lifeart** [comment]
Hi @aslushnikov! Thank you for feedback! Any chance to get functions from 
```
import { checkComponentAttribute, parseComponentSelector } from '../common/componentUtils';
```
as a part of public playwright API?

**Comment by aslushnikov** [comment]
@lifeart Even if we expose it, we won't be able to guarantee that they don't change in future, so relying on them is kinda risky.

I'd just copy them in your source!

**Comment by lifeart** [comment]
@aslushnikov, thank you! Closing MR for now.

**Pull request closed without merging**
