### PR TITLE
fix(fill): make fill work with date/time inputs

### PR DESCRIPTION
**Pull request by dgozman**
fix(fill): make fill work with date/time inputs

Date/time inputs are locale-specific, and also do not work with insertText. We just set the value on them and emulate input/change events. Note that some browsers do not support these input types just yet.

References #1331.

### CODE REVIEW

**Comment by jperl** [comment]
Can you also make fill work for  `time`, `datetime`, and`datetime-local` inputs? They will likely suffer the same issue as #1331

**Comment by dgozman** [comment]
> Can you also make fill work for `time`, `datetime`, and`datetime-local` inputs? They will likely suffer the same issue as #1331

I looked at them:
- datetime is deprecated, and renders as text in Chromium;
- time and datetime-local are very locale-specific. For example, they show AM/PM, which is not universal. They also heavily rewrite, e.g. `00:12` turns into `12:12`, and `18:55` turns into `06:55`. Typing `13:60` does all kinds of strange things. If we go this route, we better validate stuff, or just set the value.

**Comment by jperl** [comment]
Sorry tried to edit my response, to just be `time`.

I agree `datetime` is deprecated, so not worth implementing and `datetime-local` is [not supported](https://caniuse.com/#search=datetime-local) on firefox or safari so it is probably not worth implementing either.

However `time` might be valuable, at least to set the value.

**Comment by dgozman** [comment]
Update this to use a different approach.

**Review by aslushnikov — APPROVED** [review]

**Pull request merged**
