### PR TITLE
fix(core): use import for whatwg url usage

### PR DESCRIPTION
**Pull request by redabacha**
Useful when working with playwright-core in an environment like jsdom

### CODE REVIEW

**Review by dgozman — COMMENTED** [review]
Thank you for the PR! Could you please tell us more about your usecase?

I am worried that this is not sustainable going forward, because any PR could start using `URL` without an import again and there are no checks to prevent that.

**Comment by redabacha** [comment]
> Thank you for the PR! Could you please tell us more about your usecase?
> 
> 
> 
> I am worried that this is not sustainable going forward, because any PR could start using `URL` without an import again and there are no checks to prevent that.
> 
> 

hi @dgozman,

essentially trying to use the playwright-core package in jest can be quite tricky under the jsdom environment. one particular use case i have for this currently is using storybook's storyshots solution w/ playwright to create a visual regression testing platform. 

yes that's a very valid point, i was thinking to add the no-restricted-global eslint rule to catch this https://eslint.org/docs/rules/no-restricted-globals. does that sound like an okay idea?

**Comment by dgozman** [comment]
@redabacha We've seen many folks successfully running Playwright in Jest. Could you please file an issue with a repro? This is probably some edge case or some quirky setup issue.

**Comment by pavelfeldman** [comment]
You can't use Playwright in jsdom environment, it requires Node environment. As per the [docs](https://nodejs.org/api/url.html#class-url), URL is available on the global object as of Node 10, so we need environment that respects that.

**Pull request closed without merging**
