### PR TITLE
fix(electron): browser window ids out of sync

### LINKED ISSUE #6748: [BUG] Electron - race condition when evaluating multiple BrowserWindows
**Context:**
```
## System:
 - OS: Windows 10 10.0.19042
 - Memory: 16.79 GB / 31.91 GB
## Binaries:
 - Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.19.1 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
## npmPackages:
 - playwright: ^1.11.1 => 1.11.1
 ```

**Code Snippet**

I wrote an example Electron application demonstrating the issue using [Electron Fiddle](https://www.electronjs.org/fiddle): https://gist.github.com/38f12167513796435d2012df6dc2e8d0

The important snippet from the gist is in renderer.js:
```js
window.open('https://www.electronjs.org', 'firstWindow')
window.open('https://github.com/electron/electron', 'secondWindow')
```

```javascript
const path = require('path');
const { _electron: electron } = require('playwright');

(async () => {
  const app = await electron.launch({
    args: ['/path/to/saved/electron/fiddle'],
  });

  app.on('window', async page => {
    const browserWindowHandle = await app.browserWindow(page);

    const frameName = await browserWindowHandle.evaluate(
      browserWindow => browserWindow.webContents.mainFrame.name,
    );

    console.log(
      `app 'window' event [frameName:${frameName}, playwrightFrameName:${page.mainFrame().name()}, url:${page.url()}]`,
    );
  });
})();

```

**Describe the bug**

The Electron Fiddle gist linked above opens a new BrowserWindow with a button that opens two other BrowserWindows. Each of the BrowserWindows opened have their own, unique frame name and URL.

Running the test and clicking the button demonstrates some issues:
- `page.mainFrame().name()` never reads the actual frame name of the Electron BrowserWindow.
- The frame name received from evaluating the `browserWindowHandle` doesn't always match the expected `page.url()`.
   - Potential race condition?

Here's an example of  output I've seen from running this.
```
$ node test.js 
app 'window' event [frameName:firstWindow, playwrightFrameName:, url:https://www.electronjs.org/]
app 'window' event [frameName:secondWindow, playwrightFrameName:, url:https://github.com/electron/electron]
app 'window' event [frameName:firstWindow, playwrightFrameName:, url:https://www.electronjs.org/]
app 'window' event [frameName:secondWindow, playwrightFrameName:, url:https://github.com/electron/electron]
app 'window' event [frameName:firstWindow, playwrightFrameName:, url:https://github.com/electron/electron]
app 'window' event [frameName:secondWindow, playwrightFrameName:, url:https://www.electronjs.org/]
```

Notice the last two console messages in which `frameName` doesn't match the expected `url`.

### LINKED ISSUE #6760: [BUG][Electron] Page is not a BrowserWindow
**Context:**
```
## System:
 - OS: Windows 10 10.0.19042
 - Memory: 16.79 GB / 31.91 GB
## Binaries:
 - Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.19.1 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
## npmPackages:
 - playwright: ^1.11.1 => 1.11.1
 ```

**Code Snippet**

Creates two Pages: one for the BrowserWindow's WebContents and one for the BrowserView's WebContents.

```js
const { _electron: electron } = require('playwright');

(async () => {
  const app = await electron.launch();

  app.on('window', async page => {
    console.log('new window page', page.url())
  });

  await app.evaluate((electron) => {
    const win = electron.BrowserWindow.getAllWindows()[0]
    const view = new electron.BrowserView()
    view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
    view.webContents.loadURL('https://www.electronjs.org/docs/api/browser-view')
    win.addBrowserView(view)
  });
})();
```

**Describe the bug**

Playwright is conflating Electron's `BrowserWindow` abstraction as an equivalent to `Page`s. However, it's possible for Electron to have multiple `WebContents` per `BrowserWindow`.

In the method below, a new Page will increment the BrowserWindow counter.

https://github.com/microsoft/playwright/blob/3aa1471489c268ba1f43cbdee893dfbec6ebd175/src/server/electron/electron.ts#L73-L77

https://github.com/microsoft/playwright/blob/3aa1471489c268ba1f43cbdee893dfbec6ebd175/src/server/electron/electron.ts#L92-L95

This ID counter will become out of sync when the code snippet above is run. I also suspect this ID becoming out of sync is leading to the bug described in #6748.

-----

I believe that Playwright might want to redesign how it stores and retrieves BrowserWindow objects from Electron. Based on the info received from Chrome DevTools Protocol, I suspect the [`TargetID`](https://chromedevtools.github.io/devtools-protocol/tot/Target/#type-TargetID) might be the most stable identifier which could be used.

With some contributions upstream, I could see the `TargetID` being used to get the associated `WebContents`, which could then be used to get the owning `BrowserWindow`.

I'd be open to helping make this happen if it makes sense. Possible new APIs could be defined as followed:
```ts
interface WebContents {
  static fromDevToolsTargetId(targetId: string): WebContents;
}
```

Then getting the `BrowserWindow` could be done by calling `BrowserWindow.fromWebContents(webContents)`.
```ts
// playwright/src/server/electron/electron.ts
async browserWindow(page: Page): Promise<js.JSHandle<BrowserWindow>> {
  const targetId = (page as any)._delegate._targetId;
  const electronHandle = await this._nodeElectronHandlePromise;
  return await electronHandle.evaluateHandle(({ BrowserWindow, webContents }, targetId) => {
    const wc = webContents.fromDevToolsTargetId(targetId)
    return BrowserWindow.fromWebContents(wc)
  }, targetId);
}
```

### PR DESCRIPTION
**Pull request by samuelmaddock**
fixes #6760
fixes #6748

Playwright's Electron implementation is keeping track of `BrowserWindow` IDs itself which has issues that cause it to go out of sync. This has been a blocker for complex Electron apps using multiple windows or `BrowserView`s.

I've introduced a new API to Electron which will allow using the DevTools Target ID as a stable lookup identifier for `WebContents`: https://github.com/electron/electron/pull/29399

------

This PR is set as a draft to receive feedback and wait for Electron changes to be merged and released:
- v12 backport https://github.com/electron/electron/pull/30730
- v13 backport https://github.com/electron/electron/pull/30731
- v14 backport https://github.com/electron/electron/pull/30732
- v15 backport https://github.com/electron/electron/pull/30733

v12.2.0 has been released now with these changes. This PR upgrade to it since it's the minimum supported version.

### CODE REVIEW

**Comment by dgozman** [comment]
@samuelmaddock Could you please rebase this (there are merge conflicts) so I can trigger the bots? I've also undrafted for the bots to pick this up.

**Comment by samuelmaddock** [comment]
Changes have been rebased and now targets [Electron v12.2.0](https://github.com/electron/electron/releases/tag/v12.2.0) which is the minimum version including the new `webContents.fromDevToolsTargetId(targetId)` API.

**Comment by samuelmaddock** [comment]
TS error after upgrading Electron:
```
> playwright-internal@1.16.0-next tsc
> tsc -p .

node_modules/electron/electron.d.ts:6653:21 - error TS2694: Namespace 'NodeJS' has no exported member 'Require'.

6653     require: NodeJS.Require;
                         ~~~~~~~


Found 1 error.
```

It seems like `@types/node` needs to be updated. After bumping it to `^12.12.6`, I receive 57 errors. What's the preferred path forward in this case? New PR to update `@types/node`?

**Comment by mxschmitt** [comment]
@samuelmaddock we can split it in two. I'll take care that https://github.com/microsoft/playwright/pull/8837 lands soon which does exactly that, then your PR should pass.

**Comment by pavelfeldman** [comment]
I landed the roll, you can rebase this PR and we will merge.

**Comment by mxschmitt** [comment]
For the record: After this patch the minimum required versions of Electron are:

- **v12.2.0+**
- **v13.4.0+**
- v14.0.0+
- v15.0.0+

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
