### PR TITLE
feat: add getById method

### LINKED ISSUE #19763: [Feature] Add getById function
Web standards are still using id's instead of data-testid's, even if that weren't the case i don't believe a testing automation frameworks role is to advocate for change, but instead it should focus on supporting developers in their day to day and provide support for the most used standards and methods, which currently is id.

### PR DESCRIPTION
**Pull request by MindaugasMateika**
Fixes https://github.com/microsoft/playwright/issues/19763

### CODE REVIEW

**Comment by MindaugasMateika** [comment]
CLA in progress (company)

**Comment by MindaugasMateika** [comment]
@microsoft-github-policy-service agree [company="Vinted Systems, UAB}"]

**Comment by MindaugasMateika** [comment]
@microsoft-github-policy-service agree company="Vinted Systems, UAB"

**Comment by pavelfeldman** [comment]
I don't think we can do getById, but we can consider getByElementId, we'll discuss it at the api review session.

**Comment by MindaugasMateika** [comment]
> I don't think we can do getById, but we can consider getByElementId, we'll discuss it at the api review session.

Sure, let me know what you'll decide and I'll adjust  accordingly.

**Comment by pavelfeldman** [comment]
So the outcome is that unless with have 50 upvotes for a dedicated method, we should keep recommending users to use `locator('#id')`.

**Comment by MindaugasMateika** [comment]
All right, understood.

**Comment by sanamhub** [comment]
sad

**Comment by sanamhub** [comment]
Sad :(

**Comment by ZooDoo4U** [comment]
Great,  never saw this thread in order to comment.

**Comment by arukiidou** [comment]
> So the outcome is that unless with have 50 upvotes for a dedicated method, we should keep recommending users to use `locator('#id')`.

Everyone, please UP-VOTE! We need 37 more votes.

**Comment by jonathan-qa** [comment]
So, we already have 51 upvotes:

https://github.com/microsoft/playwright/issues/19763

**Comment by ZooDoo4U** [comment]
I believe this issue is closed...  But suggest making your comments on this "OPEN" issue...  To be fair as much as i'ld like this, no reason to add more work to the PW devs filtering through noise to report an issue open on another thread... 

https://github.com/microsoft/playwright/issues/19763#issuecomment-2109198731

**Pull request closed without merging**
