### PR TITLE
test(capabilities): add tests for webgl

### PR DESCRIPTION
**Pull request by JoelEinbinder**
#1032

Our webgl doesn't work in headless firefox.

### CODE REVIEW

**Review by yury-s — APPROVED** [review]

**Comment by dtuyenle** [comment]
@JoelEinbinder  Do you mind sharing how to ignore the error that firefox giving `Cannot initilize webgl` when running test ?

**Comment by JoelEinbinder** [comment]
Today you can launch Firefox with headless:false to workaround the error. You can use xvfb on Linux to hide the window.

**Comment by dtuyenle** [comment]
Hmmm we need to run it headless. Any idea how to get around the issue ?

**Comment by JoelEinbinder** [comment]
Unfortunately its a bug upstream in firefox headless. See https://bugzilla.mozilla.org/show_bug.cgi?id=1375585

**Pull request merged**
