### PR TITLE
chore(dotnet): have options derive from IOptions

### PR DESCRIPTION
**Pull request by avodovnik**

### CODE REVIEW

**Comment by avodovnik** [comment]
https://github.com/microsoft/playwright-dotnet/pull/1682

**Comment by pavelfeldman** [comment]
It is unusual to have a struct / options bag implement an interface. Could you elaborate on your plan?

**Comment by avodovnik** [comment]
Yeah, I'm aware, *however*, the reason I want to do it is, this gives me the option of having extension methods, like `.ConvertTo<T>(this IOptions origin)` which become a convenient way of converting between options, such as when calling `Frame` methods from `Page` (which is quite a lot of the cases).

**Comment by mxschmitt** [comment]
Closing it seems stale and not needed.

**Pull request closed without merging**
