### PR TITLE
chore(types): Add missing return types to browserServerImpl.ts

### PR DESCRIPTION
**Pull request by thomaschaplin**
Added missing return types to the functions inside `browserServerImpl.ts`

### CODE REVIEW

**Comment by mxschmitt** [comment]
Hi, thanks for your contribution! TypeScript does automatically [infer](https://www.typescriptlang.org/docs/handbook/type-inference.html) these types. So adding them manually is not needed. Did you face into any issues?

**Comment by thomaschaplin** [comment]
> Hi, thanks for your contribution! TypeScript does automatically [infer](https://www.typescriptlang.org/docs/handbook/type-inference.html) these types. So adding them manually is normally not needed. Did you face into any issues?

Hey, no issues - I just figured it would be more explicit! Happy for this PR to be closed though

**Comment by thomaschaplin** [comment]
Might be the same with https://github.com/microsoft/playwright/pull/6765 - let me know if these can be closed

**Comment by mxschmitt** [comment]
Yeah would be the best to keep it how it was.

**Comment by thomaschaplin** [comment]
Thanks for the quick response @mxschmitt - I've closed the PR

**Pull request closed without merging**
