### PR TITLE
feat(test): print steps by default in list reporter

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Updates #18269 to be on by default. Let's be bold!

#20955

### CODE REVIEW

**Comment by pavelfeldman** [comment]
> Let's be bold!

List is our default reporter, I'm slightly worried that we should not be breaking something that works for the majority of users. Wdyt?

**Comment by JoelEinbinder** [comment]
I'm just wondering when it switches if ever? It doesn't seem like I ever want this feature to be off as long as it works.

**Comment by pavelfeldman** [comment]
> I'm just wondering when it switches if ever? It doesn't seem like I ever want this feature to be off as long as it works.

I think it starts creating row-per step on CI, doesn't it?

**Comment by dgozman** [comment]
Closing as stale, since no consensus has been reached and branch has conflicts.

**Pull request closed without merging**
