### PR TITLE
chore: set minimum version to Node.js 14

### PR DESCRIPTION
**Pull request by mxschmitt**
Node.js 12 EOL is on the 2022-04-30, this is before our next release. So in our next release we can stop supporting Node.js 12 officially.

### CODE REVIEW

**Comment by mxschmitt** [comment]
Lets wait until Node.js 18 comes out and then bump it all-together.

**Comment by Meir017** [comment]
missed https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/stackTrace.ts#L70-L72 :)

**Comment by pavelfeldman** [comment]
Does it make anyone happy?

**Comment by mxschmitt** [comment]
As per offline discussion with @pfeldman we'll drop official support for it but don't break the users for now. So we'll keep the Node.js 12 hacks in there for now.

**Comment by pavelfeldman** [comment]
Let's add a new Node right away so that it was clear that we were saving bots for it!

**Review by dgozman — APPROVED** [review]

**Pull request merged**
