### PR TITLE
feat(ct): initial web components

### PR DESCRIPTION
**Pull request by sand4rt**
Only a simple mount without props is possible. Partial fix for https://github.com/microsoft/playwright/issues/14241

### CODE REVIEW

**Comment by pavelfeldman** [comment]
I wonder if we should stabilize the existing set before growing it further.

**Comment by sand4rt** [comment]
Yeah the same thought crossed my mind. Was too curious if it would work..

If we merge, we don't have to release it right? Maybe the other people who ask for it in the issue can start working on it too if there is a base.

Not sure if this is too much hassle. Otherwise i can leave it open or close it, it's up to you

**Comment by pavelfeldman** [comment]
We have the code in the PR, so it won't go anywhere. We can close it for now and wait for the critical mass of lit to appear.

**Comment by prashantpalikhe** [comment]
Would be great to have support for Lit components too with the same simple mount API. 

We are thinking of testing this via Storybook's play function and Playwright. But default Playwright CT will be much faster.

**Comment by sand4rt** [comment]
@prashantpalikhe Made a package for Lit and Web components with the same simple mount API until official support: https://github.com/microsoft/playwright/issues/14241#issuecomment-1368124560. 

BTW. good luck with the rebuild at KPN!😄

**Pull request closed without merging**
