### PR TITLE
fix(ts): export types explicitly

### LINKED ISSUE #14348: [BUG] Types not compatible with TS4.7 Node ESM support
**Context:**
- Playwright Version: 1.22.2
- Operating System: Linux
- Node.js version: 18.2.0
- Browser: N/A
- Extra: 

**Code Snippet**

Occurs in an ESM node file:

```ts
// Could not find a declaration file for module 'playwright'. '/home/jamesernator/scripts/node_modules/playwright/index.mjs' implicitly has an 'any' type.
//  Try `npm i --save-dev @types/playwright` if it exists or add a new declaration (.d.ts) file containing `declare module 'playwright';`ts(7016)
import playwright from "playwright";
```

**Describe the bug**

Basically the types as declared don't work with the new [`Node16`/`NodeNext` ESM support in TypeScript 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#ecmascript-module-support-in-node-js).

This happens because `playwright` only specifies a `index.d.ts` file which in TS4.7 ESM support is **only associated to index.js**. As such when importing via ESM, the resolution to `index.mjs` has no corresponding `.d.mts` file.

One resolution to this is just to include `index.d.mts` with the following line:

```ts
export * from "./index.js";
```

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/microsoft/playwright/issues/14348

### CODE REVIEW

**Review by yury-s — APPROVED** [review]
Please add a test for this.

**Review by rwoll — APPROVED** [review]

**Comment by pavelfeldman** [comment]
I won't need a test once we move to TS 4.7. We have the opposite problem though, we might need bots for earlier versions of TS.

**Comment by AviVahl** [comment]
any chance for a bugfix release with this change? just noticed it didn't resolve types in native esm mode (node16 module/moduleResolution)... :+1: 

was going to report it using the following reproduction steps:
```
mkdir playwright-node16-bug
cd playwright-node16-bug
npm init -y
npm i playwright-core typescript -D
npx tsc --init --module node16 --moduleResolution node16
echo "import playwright from 'playwright-core'; console.log(playwright);" > bug.mts
npx tsc
```

**Comment by AviVahl** [comment]
thanks for the tip. :+1: would be useful in own projects, but my team is using some dependencies with stable playwright peerDeps. 

I'm currently using `"module": "esnext", "moduleResolution": "node"`, but wanted to switch to `"node16"`, as it actually works as I'd expect (picks up "exports").

**Pull request merged**
