### PR TITLE
Feature(engine) implement angular selector engine as experimental feature

### PR DESCRIPTION
**Pull request by vitalics**
implement angular selector engine as experimental feature.

It create a walker for current scope (document, shadowRoot, Element) and finds all angular components using global angular utilities.

This usitilies used by angular dev tools

#14158 

EDIT: As for @dgozman mentioned - playwright team not yet ready to commit to angular selectors. The custom engine available at:
https://github.com/vitalics/playwright-angular-selectors

### CODE REVIEW

**Review by dgozman — COMMENTED** [review]
Thank you for the PR! Unfortunately, we are not yet ready to commit to angular selectors. I'd suggest to create a [custom engine](https://playwright.dev/docs/extensibility#custom-selector-engines) first (and use it yourself), and later on we can think about integrating it to Playwright.

**Comment by LanderBeeuwsaert** [comment]
Our team would for sure be interested in using this if it would become part of default playwright

**Comment by vitalics** [comment]
@LanderBeeuwsaert I can create a separate package and publish it to npm. I suppose not only you interesting in such selectors. And when the playwright will be ready - they will take my code 
@dgozman I think it's a good point.
After the package will be ready - I close the issue with the link to github repo

**Comment by LanderBeeuwsaert** [comment]
@vitalics that would be great!

**Comment by vitalics** [comment]
@LanderBeeuwsaert Here you're 
https://github.com/vitalics/playwright-angular-selectors

**Pull request closed without merging**
