### PR TITLE
browser(firefox): disable enterprise policies

### PR DESCRIPTION
**Pull request by JoelEinbinder**
References #8141
I am not sure if this is the right way to ﻿solve this issue, but I just disabled the enterprise policy code.

### CODE REVIEW

**Comment by mxschmitt** [comment]
Don't forget firefox-beta.

**Review by yury-s — APPROVED** [review]

**Review by aslushnikov — APPROVED** [review]

**Comment by jackyzy823** [comment]
@JoelEinbinder  since the issue #8141 still exists, can we revert this patch? since we all need group policies . see #10284

In my case i need to add self signed root certificate to test self-hosed self-signed Firefox sync service ( `ignoreHTTPSErrors` doest not work under this situation , because the request is not from HTML Pages but from Firefox  internally )

**Comment by DashwoodIce9** [comment]
+1 to revert request. Folks over at #8141 have found a way forward with [`--pref='datareporting.policy.firstRunURL=""'`](https://github.com/microsoft/playwright/issues/8141#issuecomment-2008711137) and disabling enterprise policies disables a lot of customization features such loading custom certificates (#18115). Using custom certificates is necessary for my use case, so currently I have to write a script that undoes the changes made by this commit.

**Comment by mxschmitt** [comment]
> +1 to revert request. Folks over at #8141 have found a way forward with [`--pref='datareporting.policy.firstRunURL=""'`](https://github.com/microsoft/playwright/issues/8141#issuecomment-2008711137) and disabling enterprise policies disables a lot of customization features such loading custom certificates (#18115). Using custom certificates is necessary for my use case, so currently I have to write a script that undoes the changes made by this commit.

Client Certificates are available natively in Playwright: https://playwright.dev/docs/api/class-testoptions#test-options-client-certificates since a few releases. Does this help?

**Comment by DashwoodIce9** [comment]
Sorry, no client certificates are not what I was looking for. My use case is to add certificates to browser's trust store for server side certificate verification. This can be done via use of [Enterprise Policies feature on Firefox](https://mozilla.github.io/policy-templates/#certificates--install). Commonly used for self signed server side certificates or to test internal (to a particular organization) website whose certificates were issued by a private certificate authority.

**Pull request merged**
