### PR TITLE
feat(dotnet): add revision for generated API

### PR DESCRIPTION
**Pull request by avodovnik**

### CODE REVIEW

**Review by mxschmitt — COMMENTED** [review]
Don't we generate it when we update the driver? The driver includes a file called "commitinfo" inside the package dir afaik.

**Comment by avodovnik** [comment]
> Don't we generate it when we update the driver? The driver includes a file called "commitinfo" inside the package dir afaik.

This is not related to the driver, but the docs (markdown files) we generate the API from. Those two can (and do) drift.

**Comment by pavelfeldman** [comment]
I need a hint understanding what this helps with.

**Comment by avodovnik** [comment]
> I need a hint understanding what this helps with.

I've started working on improving the .NET engineering side. There's an open [PR](https://github.com/microsoft/playwright-dotnet/pull/1618) which brings this repo as a submodule. Doing this will let me keep better track of changes as I move forward with rolling stuff. It'll also help me keep a pointer to the commit from which we generated the API for .NET. 

This marker file will help me identify drift (i.e. the submodule getting updated, but nothing would get regenerated) etc.

**Comment by mxschmitt** [comment]
Closing since it does not seem relevant anymore with the new submodule logic. (Driver version -> upstream commit sha + verification bots)

**Pull request closed without merging**
