### PR TITLE
Add function to add items to localStorage when page initializes

### PR DESCRIPTION
**Pull request by sjarmero**
For applications that use `localStorage` heavily, it is useful to be able to initialize the state of `localStorage` in certain tests, before navigating to any page. This MR adds a method, `addInitLocalStorageItems`, that provides a way of setting `localStorage` items using `addInitScript`. It also supports an `overwrite` flag. Use this to override any `localStorage` item that was already set through the browser context.

### CODE REVIEW

**Comment by mxschmitt** [comment]
Hi Sergio, thank you for your contribution! Could you please start filing a feature request for it?

**Comment by sjarmero** [comment]
> Hi Sergio, thank you for your contribution! Could you please start filing a feature request for it?

Done! Available here: https://github.com/microsoft/playwright/issues/27654

**Comment by sjarmero** [comment]
@microsoft-github-policy-service agree

**Comment by yury-s** [comment]
Closing as there are already ways to initialize local storage by either loading storage state or creating init script as described in the bug. This API would be redundant and not justified for such a niche use case.

**Pull request closed without merging**
