### PR TITLE
[Feature]: Locator.toArray method

### PR DESCRIPTION
**Pull request by vitalics**
As a part of https://github.com/microsoft/playwright/issues/12336 crates locator new api: toArray and for JS implementation - make Locator async iterable. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of)

TODO: complete examples for python, java and C#

### CODE REVIEW

**Comment by jfgreffier** [comment]
I don't see this as necessary, as it can probably be done in the user land. Also, there are several ways to manipulate Locator lists https://playwright.dev/docs/locators#lists

> TODO: complete examples for python, java and C#

You can't do something in core only for TypeScript. That would be... bad

**Comment by vitalics** [comment]
@jfgreffier In my case of using playwright is reading a tons of DOM elements and working with such ways is disgusting and you should a lot of spagetti code to do the same things. As for me it will be quite useful to add this API for locator in JS implementation, since such API can reduce the code

**Comment by pavelfeldman** [comment]
Let's publish some real-world examples into that issue first.

**Comment by vitalics** [comment]
@pavelfeldman You mean examples in docs guide, or provide separate repo where `toArray` will be helpful?

**Comment by pavelfeldman** [comment]
> @pavelfeldman You mean examples in docs guide, or provide separate repo where toArray will be helpful?

I meant let's update the issue (or better yet create a new one) with the proposal and the use cases it helps with! I'll close this PR while we are getting the proposal sorted!

**Pull request closed without merging**
