### PR TITLE
feat(base-reporter): Add tags to test output 

### PR DESCRIPTION
**Pull request by mrkstwrt**
If you switch to the [new tag syntax](https://playwright.dev/docs/test-annotations#tag-tests) added in [v1.42.0](https://github.com/microsoft/playwright/releases/tag/v1.42.0) you can no longer see tags in test logs without duplicating the tags in the test name, this PR adds the `appendTags` option to the list reporter which enables adding the tags to the end of the test name in the log.

### CODE REVIEW

**Comment by mrkstwrt** [comment]
@microsoft-github-policy-service agree

**Comment by Skn0tt** [comment]
Hi! Could you open a feature request about this? It's always good for us to first understand & discuss the usecase before we add functionality.

**Comment by mrkstwrt** [comment]
> Hi! Could you open a feature request about this? It's always good for us to first understand & discuss the usecase before we add functionality.

Sure, I've added https://github.com/microsoft/playwright/issues/32966

**Comment by pavelfeldman** [comment]
Thanks for the patch and the issue. Your change makes sense to me. I would include tags unconditionally in base.ts so that all the reporters that use base.ts would benefit from the change. I would also not wrap it with [] for now so that it was of the form

[project] › file.spec.ts:1:1 › should work @smoke

**Comment by mrkstwrt** [comment]
> Thanks for the patch and the issue. Your change makes sense to me. I would include tags unconditionally in base.ts so that all the reporters that use base.ts would benefit from the change. I would also not wrap it with [] for now so that it was of the form
> 
> [project] › file.spec.ts:1:1 › should work @smoke

Thanks for the feedback @pavelfeldman, I've made the change you suggested to always render the tags in base

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
