### PR TITLE
fix(transport): dispatch messages in separate tasks

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Fixes what I consider to be a bug in our pipe, and the same one in the non-standard `ws` module. Our protocol messages are I/O events, and therefore they should each be executed in their own task. I can not detect any performance overhead. Micro benchmarks suggest it is it equivalent in cost to a single `Promise.resolve` per protocol message.

I think there is a lot of hacks we can remove once this is landed, but I'll fix that separately in case this has any side effects.

### CODE REVIEW

**Comment by pavelfeldman** [comment]
My understanding is that this change gives us the following guarantee:

```js
session.on('event1', Promise.resolve().then(() => console.log('event1'))
session.on('event2', Promise.resolve().then(() => console.log('event2'))
> "event1"
> "event2"
```

However, the moment we replace `Promise.resolve()` with something that spans across tasks, this guarantee is going away. So by definition this change is only helpful if the entire code makes assumption that asynchronous code it runs is resolved within the task. That's a bad assumption to have.


To me, whenever I see a promise, I need to care about the resolution order. This patch adds a single arbitrary place of code that makes all microtasks fulfilled before the next event. This gives us some false promises that if we rely upon will bite us.

**Comment by pavelfeldman** [comment]
To be clear, session is already strict in terms of acking to the commands and emitting events, so in case of:

```js
session.on('consoleAPICalled', v => console.log(v);
console.log(await session.send('Page.evaluate("console.log(1);console.log(2);3")'));
> 1
> 2
> 3
```

the right order is always guaranteed.

**Comment by aslushnikov** [comment]
Love it! I re-wrote it a bit with some commentary

```js
// Playwright uses WebSockets as one of the options to communicate with the browser.
// It also implements it's own "PipeTransport" to read messages from
// sockets and dispatch them to clients.
//
// In node.js, we use `ws` 
// Now, both `ws` and Playwright pipe implementation might dispatch
// several messages in the same task. This is very unfortunate, since
// all IO is expected to be dispatched in a separate tasks.
//
// The purpose of IOTaskQueue is to dispatch all
// messages from websocket and pipe transport in separate tasks.
// On different platforms, this is achieved in different ways.
function createIOTaskQueue() {
  if (!isNode)
    return new WebIOTaskQueue();
  const nodeVersion = parseInt(process.versions.node, 10);
  return nodeVersion >= 11 ? new Node11AndLaterIOTaskQueue() : new Node10IOTaskQueue();
}

// In node 11 and following, we can simply call `setImmediate` to run a piece of code
// in a separate task.
export class Node11AndLaterIOTaskQueue {
  dispatchInNextTask(callback) {
    setImmediate(callback);
  }
}

// Unlike Node 11, Node 10 and less have a bug with Task and MicroTask execution order:
// - https://github.com/nodejs/node/issues/22257
//
// So we can't simply run setImmediate to dispatch code in a following task.
// However, we can run setImmediate from-inside setImmediate to make sure we're getting
// in the following task.
export class Node10IOTaskQueue {
  constructor() {
    this._callbacks = [];
    this._isSpinning = false;
    this._doDispatchMessage = this._doDispatchMessage.bind(this);
  }

  dispatchInNextTask(callback) {
    this._callbacks.push(callback);
    if (!this._isSpinning) {
      this._isSpinning = true;
      setImmediate(this._doDispatchMessage);
    }
  }

  _doDispatchMessage() {
    const callback = this._callbacks.shift();
    if (callback) {
      setImmediate(this._doDispatchMessage);
      // Make sure to call callback() as the last thing since it's an
      // untrusted code that might throw.
      callback();
    } else {
      this._isSpinning = false;
    }
  }
}

// In Web, all IO callbacks (e.g. WebSocket callbacks)
// are dispatched into separate tasks, so there's no need
// to do anything extra.
export class WebIOTaskQueue {
  dispatchInNextTask(callback) {
    callback();
  }
}


```

**Comment by JoelEinbinder** [comment]
This was a tricky one! I dumped all of my thoughts into an [explainer](https://joel.tools/microtasks), and I'll try to send a patch to `ws` soon.

**Review by aslushnikov — APPROVED** [review]

**Pull request merged**
