### PR TITLE
chore: fix modification dates in driver

### PR DESCRIPTION
**Pull request by mxschmitt**

### CODE REVIEW

**Comment by campersau** [comment]
`tar` also supports `--touch` so this
https://github.com/microsoft/playwright/blob/70603d76858d5a62e7bd725309d3aa03bef186c6/utils/build/build-playwright-driver.sh#L33
could be change to:
```bash
tar -xzf ./output/playwright-core.tgz -C ./output/playwright-${SUFFIX}/ --touch
```
instead.

**Review by yury-s — APPROVED** [review]

**Comment by yury-s** [comment]
> [`tar`](https://linux.die.net/man/1/tar) also supports `--touch` so this

Seem like it is not supported on macOS :(

**Comment by aslushnikov** [comment]
How come this was working before? Is this a regression? If it is, what triggered it?

**Comment by campersau** [comment]
To support different publish modes in `playwright-dotnet` the files are now included via `msbuild`, which checks for the modified date, instead of manually copying them every time.
See https://github.com/microsoft/playwright-dotnet/pull/1955#issuecomment-1019148707

**Pull request merged**
