### PR TITLE
test: add test for time/timeLog/timeEnd formatting

### PR DESCRIPTION
**Pull request by mxschmitt**
test for #10580

### CODE REVIEW

**Review by pavelfeldman — CHANGES_REQUESTED** [review]
What exactly is wrong in FF?

**Comment by mxschmitt** [comment]
> What exactly is wrong in FF?

firefox:

expected: fooo 25.04 ms
actual: fooo

**Comment by pavelfeldman** [comment]
> expected: fooo 25.04 ms
> actual: fooo

I don't think this is expected. I guess time comes as a first argument.

**Comment by mxschmitt** [comment]
> > expected: fooo 25.04 ms
> > actual: fooo
> 
> I don't think this is expected. I guess time comes as a first argument.

image

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
