### PR TITLE
fix: load event with non-url subframe

### LINKED ISSUE #9028: [Bug]: Timeout error when the page is already loaded
### Playwright version

1.14.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### Other information

python 3.8.8

### What happened? / Describe the bug

Always, but only the first time when the program does page.goto, playwright despite correctly loading the page throw timeout error. When I will do while loop with lets say 5 tries then second try will work without any issue. So the first try always throw for some reason timeout error.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

def login(email:str, password:str) -> None:
    base = "https://www.nike.com/ca/launch/t/womens-air-max-furyosa-night-green"
    with sync_playwright() as playwright:
        browser = playwright.firefox.launch(headless=False)
        page = browser.new_page()
        try:
            page.goto(base, timeout=20000)
        except Exception as e:
            print("Error: " + str(e))
        page.click("//button[@data-qa='accept-cookies']")
        page.click("text=Join / Log In") # 
        page.fill(".emailAddress input", str(email))
        page.fill(".nike-unite-password-input input", str(password))
        page.click(".loginSubmit input")
        browser.close()


if __name__ == "__main__":
    login("email","password")
```

### Relevant log output

_No response_

### LINKED ISSUE #12182: [BUG]  page.goto: Timeout XXXms exceeded. No load or domcontentloaded event fired
**Context:**
- Playwright Version: 1.19.1
- Operating System: Mac
- Node.js version: 16.11.1
- Browser: Firefox
- Extra: 
- executablePath: '/Users/navin/Library/Caches/ms-playwright/firefox-1316/firefox/Nightly.app/Contents/MacOS/firefox',
    headless: false,
    args: [
      '--width=1280',
      '--height=720',
    ],

```javascript
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch({
    headless: false,
    args: [
      '--width=1280',
      '--height=720',
    ],
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  page.setDefaultTimeout(60000);
  // fire async navigation
  await page.goto('https://www.nike.com/', {
    waitUntil: 'load',
  });
  console.log('Done')
  await page.close()
  await browser.close()  
})();
```

Script opens the nike.com url but stuck on goto. No additional requests in the devtool. Visually it stopes the loading, web site  looks correct (with all css/js), but got never finishes
```bash
DEBUG=pw:api node index.js
 pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +4s
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +23ms
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +619ms
  pw:api   navigated to "about:blank" +38ms
  pw:api <= browserContext.newPage succeeded +6ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://www.nike.com/", waiting until "load" +6ms
  pw:api   "commit" event fired +862ms
  pw:api   navigated to "https://www.nike.com/il/" +0ms
  pw:api   "commit" event fired +2s
  pw:api   navigated to "https://unite.nike.com/session.html?appVersion=912&experienceVersion=912" +0ms
  pw:api   "commit" event fired +107ms
  pw:api   navigated to "https://api.nike.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/fp" +0ms
  pw:api   "commit" event fired +23ms
  pw:api   navigated to "https://unite.nike.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/fp" +1ms
  pw:api   "commit" event fired +5s
  pw:api   navigated to "https://www.googletagmanager.com/ns.html?id=GTM-NTF2X45" +0ms
  pw:api   "commit" event fired +828ms
  pw:api   navigated to "about:blank" +0ms

  pw:api   "commit" event fired +17ms
  pw:api   navigated to "about:blank" +1ms

  pw:api   "commit" event fired +51ms
  pw:api   navigated to "https://bid.g.doubleclick.net/xbbe/pixel?d=KAE" +0ms
  pw:api   "commit" event fired +29ms
  pw:api   navigated to "https://tr.snapchat.com/cm/i?pid=20634084-7fa1-4691-8aec-fefe00263e00" +0ms
  pw:api   "commit" event fired +406ms
  pw:api   navigated to "https://www.pinterest.com/ct.html" +0ms
  pw:api <= page.goto failed +49s
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: Timeout 60000ms exceeded.
=========================== logs ===========================
navigating to "https://www.nike.com/", waiting until "load"
============================================================
    at /Users/navin/Downloads/goto/index.js:19:14 {
  name: 'TimeoutError'
}
```

same behavior for waitUntill: domcontentloaded or any other

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
fixes: #12182
fixes: #9028

### CODE REVIEW

**Review by dgozman — COMMENTED** [review]
Very nice find, thank you for the PR! However, both linked issues are Firefox-specific, so I believe the proper fix would be in Firefox instrumentation that does not send any load/domcontentloaded events. Adding @aslushnikov for any ideas.

**Comment by liuxingbaoyu** [comment]
Thanks for your review!

It seems that it's not just firefox that has the problem.

Although only changing firefox can solve these two issues, the three browsers have not been able to pass the test completely before.

Firefox, webkit, and chrome are all inconsistent for javascript|text/html frame loading events.

And it looks like not waiting for non-url frames has little effect on behavior, so I went with this solution.

**Comment by zhanglei4333** [comment]
Hello, can I download the latest package to solve this problem, or change my case according to your code

**Comment by liuxingbaoyu** [comment]
This pr has not been merged yet.

You can cherry-pick and build it yourself.

Or modify the files in node_module.

**Comment by aslushnikov** [comment]
@liuxingbaoyu thank you for the PR and awesome tests.

So indeed each browser struggles differently. Here's the summary:

- `javascript-src` iframe
  * chromium: ❌ never fires `"networkidle"` for iframe
  *   webkit: ✅
  *  firefox: ❌ never fires `"load"` and `"networkidle"` for iframe
- `data-src` iframe
  * chromium: ✅
  *   webkit: ❌ never fires `"networkidle"` for iframe
  *  firefox: ❌ never fires `"networkidle"` for iframe
- `blob-src` iframe
  * chromium: ❌ never fires `"networkidle"` for iframe
  *   webkit: ✅
  *  firefox: ❌ never fires `"domcontentloaded"`, `"load"` and  `"networkidle"` for iframe

Let me see if it's worth it fixing upstream in browsers or on our side.

**Comment by zhanglei4333** [comment]
> This pr has not been merged yet.
> 
> You can cherry-pick and build it yourself.
> 
> Or modify the files in node_module.
Excuse me, how can I modify node_ Module file, which package needs to be modified

**Comment by zhanglei4333** [comment]
> This pr has not been merged yet.
> 
> You can cherry-pick and build it yourself.
> 
> Or modify the files in node_module.

My node_module There is no playwright-core package in the module file

**Comment by zhanglei4333** [comment]
> 
After changing according to your idea, my original case can't run. Have you encountered this problem

**Comment by dgozman** [comment]
Most of these issues have been fixed, thank you for the PR!

**Pull request closed without merging**
