### PR TITLE
chore: added envinfo to the bug issue template

### LINKED ISSUE #2027: [Feature] Usage of envinfo to supply information in bug reports
Currently the bug report template requires these fields:

```sh
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node version: [e.g. 10.12, 10.14]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]
```

If you start using https://github.com/tabrindle/envinfo you can get more detailed information, especially if you push a preset to the to the repo to this file https://github.com/tabrindle/envinfo/blob/master/src/presets.js. It can then be executed like:

```sh
npx envinfo --preset playwright
```

And you can just ask users to execute that in their environment and copy&paste the results. It would also make Playwright more official being seen as a preset there 😃 Just an idea - perfectly fine to close if you do not want this.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes #2027

~Can be merged as soon a new version of envinfo is released.~

### CODE REVIEW

**Comment by thernstig** [comment]
Is there any sense in leaving the `**Context:**` parts now? All answers answered by the npx command can be removed from there. The only thing that needs to stay in some sense is the "browsers" and "extras". Would it be possible to merge the npx part with the `Context` part to be less verbose?

(Verbose bug report templates scare people)

**Comment by thernstig** [comment]
Should this still stay in some way?

`- Browser: [e.g. All, Chromium, Firefox, WebKit]`

npx won't give that information, which I assume is quite important for Playwright bugs?

**Comment by pavelfeldman** [comment]
It is saying

```
No "playwright" preset found.
```

to me

**Comment by mxschmitt** [comment]
> It is saying
> 
> ```
> No "playwright" preset found.
> ```
> 
> to me

Yep that's why the PR is in draft and as mentioned in the PR description we have to wait that the new update will be published.

**Comment by arjun27** [comment]
I think we can merge this now! 

```
➜  ~ npx envinfo --preset playwright
npx: installed 1 in 0.993s

  System:
    OS: macOS 10.15.6
    Memory: 2.61 GB / 32.00 GB
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
> I think we can merge this now!
> 
> ```
> ➜  ~ npx envinfo --preset playwright
> npx: installed 1 in 0.993s
> 
>   System:
>     OS: macOS 10.15.6
>     Memory: 2.61 GB / 32.00 GB
>   Binaries:
>     Node: 14.5.0 - /usr/local/bin/node
>     Yarn: 1.22.4 - /usr/local/bin/yarn
>     npm: 6.14.5 - /usr/local/bin/npm
>   Languages:
>     Bash: 3.2.57 - /bin/bash
> ```

Yep, made one follow up [PR](https://github.com/tabrindle/envinfo/pull/188), so the output gets:
```

  System:
    OS: macOS 10.15.6
    Memory: 1.18 GB / 16.00 GB
  Binaries:
    Node: 13.12.0 - /var/folders/nq/zpr698s164v26n4v45mfkzw80000gq/T/yarn--1598600290051-0.6392841704017853/node
    Yarn: 1.22.4 - /var/folders/nq/zpr698s164v26n4v45mfkzw80000gq/T/yarn--1598600290051-0.6392841704017853/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright-chromium: 1.3.0 => 1.3.0 
    playwright-video: 2.3.1 => 2.3.1 

```

**Review by arjunattam — APPROVED** [review]
Edited to make it more terse

**Pull request merged**
