### PR TITLE
docs: Added types to custom reporter typescript example

### PR DESCRIPTION
**Pull request by ValorHeart**
Signed-off-by: Adi <61405630+ValorHeart@users.noreply.github.com>

### CODE REVIEW

**Comment by ValorHeart** [comment]
Not sure what is the reason regarding 'tree is dirty' error, will be glad for assistance with that.

**Comment by mxschmitt** [comment]
You need to run `npm ci && npm run build` to re-generate types.

**Comment by ValorHeart** [comment]
@microsoft-github-policy-service agree

**Comment by ValorHeart** [comment]
> You need to run `npm ci && npm run build` to re-generate types.

Thanks! Fixed

**Comment by pavelfeldman** [comment]
Aren't all these types inferred? We don't annotate inferred type names, IDEs and compilers will do the right thing.

**Review by pavelfeldman — APPROVED** [review]

**Comment by pavelfeldman** [comment]
Actually, I approved it too soon. We don't like explicit type annotation when they can be inferred. Could you show the entirety of the file that WebStrom could not infer?

**Comment by ValorHeart** [comment]
@pavelfeldman Attached example project, notice how the auto-complete doesn't work
[example.zip](https://github.com/microsoft/playwright/files/10527657/example.zip)

**Pull request merged**
