### PR TITLE
devops: add yarn and git in the docker container

### LINKED ISSUE #3529: [Feature] Additions to docker instance?
I'm attempting to use Playwright with CircleCI and when doing a `checkout` I get the following warning:
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
```
I later get a message about `yarn` not being available as well.

Would it be possible to add these to the image?

### PR DESCRIPTION
**Pull request by aslushnikov**
This will help consuming docker image as an env for test execution.

Fixes #3529.

### CODE REVIEW

**Review by yury-s — APPROVED** [review]

**Comment by Westbrook** [comment]
Nice! How long does it usually take for something like this to become available when requesting from CircleCI for example?

**Comment by arjun27** [comment]
@westbrook you can use this today with the `next` tag: `microsoft/playwright:next`. The `latest` tag will be moved on the next release (some time in early September)

**Comment by Westbrook** [comment]
Thanks for the info @arjun27, would that look like: `mcr.microsoft.com/playwright:next` for usage in something like CircleCI? I'm not seeing the addition of `yarn` and `git` when leveraging that image.

**Comment by arjun27** [comment]
Thanks for checking. I was able to repro this locally: `mcr.microsoft.com/playwright:next` does not have git/yarn installed. This was [the Actions run](https://github.com/microsoft/playwright/runs/1034601582?check_suite_focus=true) that pushed the `playwright:next` and `playwright:sha-3ea3cf0` tags. 

* `mcr.microsoft.com/playwright:sha-3ea3cf0` is working locally with git and yarn, and can be used as a step-gap before the next release
* `mcr.microsoft.com/playwright:next` not working is a bug and needs investigation. My observations:
  * The docker push to `next` tag from the Actions run was successful
  * On ACR portal, I can see that the `next` tag was updated with the same timestamp as `sha-3ea3cf0`
  * Pulling `playwright.azurecr.io/public/playwright:next` works – it has git/yarn on it
  * The mirroring between the playwright ACR subscription and mcr.microsoft.com seems to be broken, and `mcr.microsoft.com/playwright:next`
  * I'll reach out to the MCR team since this seems to be an issue at that layer

fyi @aslushnikov

**Comment by arjun27** [comment]
@westbrook, the `next` tag should be working now. I've verified it locally.

**Comment by Westbrook** [comment]
Cool. I will check that out, the `:sha-3ea3cf0` had gotten me on the right path, at least enough to find one more thing I'd like added to the image, but I'll create a new issue to track that. Thanks for all your help on the @arjun27!

**Pull request merged**
