### PR TITLE
Ct vite config async

### PR DESCRIPTION
**Pull request by yeion7**
This PR adds the ability to `ctViteConfig` be async 

This allows read the vite config file by importing the `loadConfigFromFile` function from the `vite` package and using it within the `ctViteConfig` function. The config object is then returned, in this way it's possible to fully reuse the existing vite config

```
import { loadConfigFromFile } from "vite"

const config = {
    use: {
        async ctViteConfig() {
            const { config } = await loadConfigFromFile(
                resolve(__dirname, "./vite.config.js")
            );

            return config
        }
    }
}

export default config
```

### CODE REVIEW

**Comment by yeion7** [comment]
> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree

**Comment by sand4rt** [comment]
Related to: https://github.com/microsoft/playwright/issues/19694

**Comment by pavelfeldman** [comment]
You should be able to do the following:

```js
import { loadConfigFromFile } from "vite"

const config = {
    use: {
        ctViteConfig: async ({}, use) => {
            const { config } = await loadConfigFromFile(
                resolve(__dirname, "./vite.config.js")
            );
            await use(config);
        });
    }
}

export default config
```

**Comment by yeion7** [comment]
> You should be able to do the following:

Interesting thing, I would not have imagined that it could be done reading the type definition of `ctViteConfig`

I think part of the inspiration of this is, other tools that have integration with vite, follow this kind of format, for example storybook

https://github.com/storybookjs/builder-vite#customize-vite-config

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
