### PR TITLE
fix(chromium): Add error message to asset when there is one.

### PR DESCRIPTION
**Pull request by ghost**
[195 - 200] -- Prevent an error from being thrown when the user manually closes the sesstion. This is something which happens when you launch the browser with persistent context.

[202] -- If the object has an error message it should pass that on to asset so that the end user gets something useful instead of 'Assertion Error'. This line will add the error message to the assert call which will then repsent it to the user.

### CODE REVIEW

**Comment by dgozman** [comment]
@MakingStuffs Do you mind filing an issue that explains the problem? Otherwise, I am not sure what are we fixing. A repro that we could run would be ideal.

**Comment by MakingStuffs** [comment]
Hi @dg

> @MakingStuffs Do you mind filing an issue that explains the problem? Otherwise, I am not sure what are we fixing. A repro that we could run would be ideal.
Hi mate, sorry I should have probably labelled it as a chore. The update is just ensuring two things: 

1. That the user closing the browser manually is ignored when in launched with persistent context, as with using the normal launch function
2. That any error message provided in to the if block is passed to assert as the current implementation of launchPersistentContext just gives a very unhelpful error message of `Assertion error` due to the fact that the message is not being passed, only the `!object.id` is.

**Comment by MakingStuffs** [comment]
Here is the repo I forked: https://github.com/MakingStuffs/playwright

**Comment by dgozman** [comment]
> That the user closing the browser manually is ignored when in launched with persistent context, as with using the normal launch function

For this part, we would love to see a repro script, to be aligned on the issue. I don't think that ignoring `Session with given id not found` errors is the right solution, but we will gladly help with the right fix if we know the problem exactly.

> That any error message provided in to the if block is passed to assert as the current implementation of launchPersistentContext just gives a very unhelpful error message of Assertion error due to the fact that the message is not being passed, only the !object.id is.

This is a good point! If you'd make a PR with just this change, I'll merge it right away.

**Comment by MakingStuffs** [comment]
> > That the user closing the browser manually is ignored when in launched with persistent context, as with using the normal launch function
> 
> For this part, we would love to see a repro script, to be aligned on the issue. I don't think that ignoring `Session with given id not found` errors is the right solution, but we will gladly help with the right fix if we know the problem exactly.
> 
> > That any error message provided in to the if block is passed to assert as the current implementation of launchPersistentContext just gives a very unhelpful error message of Assertion error due to the fact that the message is not being passed, only the !object.id is.
> 
> This is a good point! If you'd make a PR with just this change, I'll merge it right away.

No probs I will do that today :) Should I close this one and start fresh?

**Comment by dgozman** [comment]
> Should I close this one and start fresh?

That's up to you. If you repurpose this PR that would also be fine.

**Comment by MakingStuffs** [comment]
> > Should I close this one and start fresh?
> 
> That's up to you. If you repurpose this PR that would also be fine.

Nice one mate I have removed the regex check for lost session ID and just kept the change passing the error message to assert :) thank you for your help

**Review by dgozman — APPROVED** [review]

**Pull request merged**
