### PR TITLE
fix(docker): Update nativeDeps.ts

### PR DESCRIPTION
**Pull request by eeoun**
add chromium dependencies on ubuntu:focal, it show error when using chromium.
not sure Bionic works fine or not.

### CODE REVIEW

**Comment by mxschmitt** [comment]
What kind of error does it show and is it reproducible?

The tests run daily against the Docker images which are currently passing: https://github.com/aslushnikov/devops.aslushnikov.com/runs/2214823185?check_suite_focus=true

**Comment by gctmt** [comment]
I'm using a custom Dockerfile to reduce package size.
copy chromium from 
```
mcr.microsoft.com/playwright   focal      2012fa7677f5
```
and use ` ubuntu:focal f643c72bc252`default `nodejs package`

when starting the container, boom. And when I finish install and restart again, everything looks fine. No more error message.
```shell
(node:7) UnhandledPromiseRejectionWarning: browserType.launch: Protocol error (Browser.getVersion): Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/chromium-857950/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-Z90HuI --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
<launched> pid=18
[pid=18][err] /ms-playwright/chromium-857950/chrome-linux/chrome: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
[pid=18] <process did exit: exitCode=127, signal=null>
=========================== logs ===========================
<launching> /ms-playwright/chromium-857950/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-Z90HuI --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
<launched> pid=18
[pid=18][err] /ms-playwright/chromium-857950/chrome-linux/chrome: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
[pid=18] <process did exit: exitCode=127, signal=null>
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/app/node_modules/playwright/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/app/node_modules/playwright/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/app/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at _wrapApiCall (/app/node_modules/playwright/lib/client/browserType.js:64:67)
    at BrowserType._wrapApiCall (/app/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at BrowserType.launch (/app/node_modules/playwright/lib/client/browserType.js:55:21)
    at /app/src/local.js:13:49
    at Object.<anonymous> (/app/src/local.js:14:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Review by mxschmitt — APPROVED** [review]

**Comment by mxschmitt** [comment]
LGTM, thanks for the additional details!

**Review by yury-s — APPROVED** [review]
Interestingly, but after installing this lib chromium is still failing for me with the following traces:

```sh
  pw:browser [pid=5611][err] Received signal 6 +0ms                                                                                      
  pw:browser [pid=5611][err] #0 0x56380d468c49 base::debug::CollectStackTrace() +5ms         
  pw:browser [pid=5611][err] #1 0x56380d3d6ab3 base::debug::StackTrace::StackTrace() +8ms               
  pw:browser [pid=5611][err] #2 0x56380d4687f0 base::debug::(anonymous namespace)::StackDumpSignalHandler() +7ms       
  pw:browser [pid=5611][err] #3 0x7f3b78e7d3c0 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf) +0ms
  pw:browser [pid=5611][err] #4 0x7f3b7751218b gsignal +0ms                                                                              
  pw:browser [pid=5611][err] #5 0x7f3b774f1859 abort +0ms                                                                                
  pw:browser [pid=5611][err] #6 0x56380d467e15 base::debug::BreakDebugger() +7ms                                                         
  pw:browser [pid=5611][err] #7 0x56380d3e7998 logging::LogMessage::~LogMessage() +8ms                                                   
  pw:browser [pid=5611][err] #8 0x56380d3e804e logging::LogMessage::~LogMessage() +7ms                                                   
  pw:browser [pid=5611][err] #9 0x56380a9899f8 x11::InitXlib() +0ms                                                                      
  pw:browser [pid=5611][err] #10 0x56380a989bb9 x11::XlibDisplay::XlibDisplay() +1ms                  
  pw:browser [pid=5611][err] #11 0x56380a982d90 x11::Connection::GetXlibDisplay() +0ms                          
  pw:browser [pid=5611][err] #12 0x56380e7d9137 gl::init::InitializeGLOneOffPlatformX11() +10ms           
  pw:browser [pid=5611][err] #13 0x56380e7d713b gl::init::InitializeGLOneOffPlatformImplementation() +10ms                               
  pw:browser [pid=5611][err] #14 0x56380e7d6ec1 gl::init::(anonymous namespace)::InitializeGLOneOffPlatformHelper() +10ms                
  pw:browser [pid=5611][err] #15 0x56380e7d6fbc gl::init::InitializeGLNoExtensionsOneOff() +10ms                                         
  pw:browser [pid=5611][err] #16 0x56380f1eb254 gpu::GpuInit::InitializeAndStartSandbox() +11ms                                          
  pw:browser [pid=5611][err] #17 0x563811aabf04 content::GpuMain() +19ms                                                                 
  pw:browser [pid=5611][err] #18 0x56380d373f83 content::RunZygote() +7ms                                                                
  pw:browser [pid=5611][err] #19 0x56380d375262 content::ContentMainRunnerImpl::Run() +7ms
  pw:browser [pid=5611][err] #20 0x56380d37283d content::RunContentProcess() +7ms                               
  pw:browser [pid=5611][err] #21 0x56380d3731dd content::ContentMain() +7ms                               
  pw:browser [pid=5611][err] #22 0x56380d3d0e25 headless::(anonymous namespace)::RunContentMain() +7ms                                   
  pw:browser [pid=5611][err] #23 0x56380d3d0bce headless::RunChildProcessIfNeeded() +7ms                                                 
  pw:browser [pid=5611][err] #24 0x56380d3cf445 headless::HeadlessShellMain() +7ms             
  pw:browser [pid=5611][err] #25 0x56380a43f765 ChromeMain +21ms                                                                         
  pw:browser [pid=5611][err] #26 0x7f3b774f30b3 __libc_start_main +0ms                
  pw:browser [pid=5611][err] #27 0x56380a43f5aa _start +21ms                                                                             
  pw:browser [pid=5611][err]   r8: 0000000000000000  r9: 00007ffef7bd6240 r10: 0000000000000008 r11: 0000000000000246 +0ms
  pw:browser [pid=5611][err]  r12: 00003ebc00304280 r13: 00007ffef7bd64a0 r14: 00003ebc00304290 r15: aaaaaaaaaaaaaaaa +0ms
  pw:browser [pid=5611][err]   di: 0000000000000002  si: 00007ffef7bd6240  bp: 00007ffef7bd6490  bx: 00007f3b76152d80 +0ms
  pw:browser [pid=5611][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 00007f3b7751218b  sp: 00007ffef7bd6240 +0ms
  pw:browser [pid=5611][err]   ip: 00007f3b7751218b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000 +0ms
  pw:browser [pid=5611][err]  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
```

**Pull request merged**
