### PR TITLE
chore: remove page.queryObjects API

### PR DESCRIPTION
**Pull request by pavelfeldman**

### CODE REVIEW

**Review by yury-s — APPROVED** [review]

**Comment by subzey** [comment]
Will `queryObjects` be reintroduced?

**Comment by yury-s** [comment]
@subzey we don't have any immediate plans on reintroducing this. Out of all browsers only Chromium support this and we'd need to have a good rational for implementing it in other browsers. The cost of that didn't seem justified given the limited utility of the feature and more comprehensive heap analysis tools that exist in the browsers.

With that said, if you have a strong case for that,  please open an issue, we can reconsider that.

**Comment by subzey** [comment]
To be honest, I don't really need it to be implemented in other browsers.

In my case the `queryObjects()` is used to check if a JS component has cleaned its DOM subscriptions - `addEventListener`, `setTimeout`, or `rAF` - when it is destroyed.

The lifecycle test looks like this:
- Create and init some component.
- Remove and destroy it.
- Run `queryObjects()` to check if it has been (or can be) garbage collected.
- If there are still dangling instances, fail the test.

This method is really handy and gives much more information than something like "Used heap size increased". The lack of support in other browsers is really not an issue: if it leaks it leaks everywhere.

Can you please suggest something to replace it?

Or maybe there's a way to invoke it using raw CDP commands? I've tried to [use the `ChromiumSession`](https://github.com/microsoft/playwright/blob/master/docs/api.md#class-chromiumsession), but no luck so far.

**Comment by yury-s** [comment]
I get your point about more detailed information that `queryObjects()` provides but we want to keep feature parity across browsers and this one is not at the top of the list at the moment. 

You should still be able to achieve the same result in Chromium via raw protocol using the [`ChromiumSession`](https://github.com/microsoft/playwright/blob/master/docs/api.md#class-chromiumsession) and [Runtime.queryObjects](https://vanilla.aslushnikov.com/?Runtime.queryObjects) command. You'll need to evaluate `prototypeObjectId` in the new session.

**Pull request merged**
