### PR TITLE
chore(deps): bump `https-proxy-agent` version

### LINKED ISSUE #2715: [BUG] [Dependency] Update `https-proxy-agent`
**Context:**
- Playwright Version: 1.1.1
- Operating System: N/A
- Node version: N/A
- Browser: N/A
- Extra: N/A

**Describe the bug**

Looking at `playwright`'s [dependency graph](https://npm.anvaka.com/#!/view/2d/playwright) I noticed that it's relying on an outdated `https-proxy-agent` version. Because of this, there are two versions of `debug` installed per every install of `playwright`. Luckily, it's your only duplicate.

While seemingly minor, you're still relying on outdated deps.

`https-proxy-agent@5.x` exists – it still supports Node >= 10 and [shares your `debug` link](https://npm.anvaka.com/#!/view/2d/https-proxy-agent/5.0.0)

### PR DESCRIPTION
**Pull request by lukeed**
See package's [release notes](https://github.com/TooTallNate/node-https-proxy-agent/releases)

Closes #2715

### CODE REVIEW

**Comment by pavelfeldman** [comment]
Linter seems unhappy. @aslushnikov, any idea why?

**Comment by aslushnikov** [comment]
@pavelfeldman `https-proxy-agent` 5.0.0 comes with index.d.ts that contains the following lines:

```js
import http from 'http';
```

The proper import statement is `import * as http from 'http'; the reason it works for them is because they use `esModuleInterop` option in their tsconfig.

@JoelEinbinder how do we go about this? I'm confused.

**Comment by JoelEinbinder** [comment]
> @JoelEinbinder how do we go about this? I'm confused.

We can just enable `esModuleInterop` if nothing else breaks? I'll try it out.

**Comment by aslushnikov** [comment]
Closing in favor of https://github.com/microsoft/playwright/pull/2777

**Comment by lukeed** [comment]
Not sure why that couldn't have been pushed into here.

**Pull request closed without merging**
