### PR TITLE
fix(ui): show stack frames in ui mode

### PR DESCRIPTION
**Pull request by spiderhands**
#29558, #29500

### CODE REVIEW

**Comment by spiderhands** [comment]
@microsoft-github-policy-service agree

**Review by yury-s — DISMISSED** [review]
This is undoing what was explicitly done in https://github.com/microsoft/playwright/pull/21590, let's make sure https://github.com/microsoft/playwright/issues/29558#issuecomment-1954810926 is addressed first and there is a good reason for reverting this mode.

**Comment by pavelfeldman** [comment]
Looks good. A test caught your changes. You can update it to something like this:

```js
    test('should show trace source', async ({ runInlineTest, page, showReport }) => {
      const result = await runInlineTest({
        'playwright.config.js': `
          module.exports = { use: { trace: 'on' } };
        `,
        'a.test.js': `
          import { test, expect } from '@playwright/test';
          async function evaluateWrapper(page, expression) {
            await page.evaluate(expression);
          }
          test('passes', async ({ page }) => {
            await evaluateWrapper(page, '2 + 2');
          });
        `,
      }, { reporter: 'dot,html' }, { PW_TEST_HTML_REPORT_OPEN: 'never' });
```

run this to check it:

```sh
npm run ttest reporter-html.spec.ts:438
```

**Comment by spiderhands** [comment]
@pavelfeldman I've updated the PR and the tests are passing now.

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
