### PR TITLE
test: navigator.clipboard is present

### LINKED ISSUE #18901: [BUG] navigator.clipboard not available on WebKit
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux
- Node.js version: 16
- Browser: WebKit

**Code Snippet**

```javascript
const playwright = require('playwright');

(async () => {
  const browser = await playwright.webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://example.com/');
  await page.getByText('More').click();
  console.log(await page.evaluate(() => window.isSecureContext));
  console.log(await page.evaluate(() => navigator.clipboard));
  await page.evaluate(() => navigator.clipboard.writeText('Text'));
  await browser.close();
})();
```

**Describe the bug**

The website is in secure context but still I got the following logs for the above snippet on https://try.playwright.tech/ and also on the CI env (Linux):

```
true
undefined
node:internal/process/promises:252
triggerUncaughtException(err, true /* fromPromise */);
^

page.evaluate: TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText')
at [eval]:12:14
```

It works on my local development env (macOS).

### PR DESCRIPTION
**Pull request by yury-s**
Fixes #18901

### CODE REVIEW

**Review by aslushnikov — APPROVED** [review]

**Review by dgozman — APPROVED** [review]

**Comment by oskarhane** [comment]
How does this fix #18901?
The issue is still there, so either something's wrong with the test in this PR, or there's an unreleased fix somewhere that's not being referenced here.

Like the issue says, it works fine using MacOS, but not in Linux (CI - GitHub Actions).

**Comment by mxschmitt** [comment]
> How does this fix #18901?
> 
> The issue is still there, so either something's wrong with the test in this PR, or there's an unreleased fix somewhere that's not being referenced here.
> 
> 
> 
> Like the issue says, it works fine using MacOS, but not in Linux (CI - GitHub Actions).

The fix is inside https://playwright.dev/docs/canary-releases and gets released in v1.31.

**Comment by oskarhane** [comment]
Thanks @mxschmitt! 
When is the planned release for 1.31?

**Comment by aslushnikov** [comment]
ETA is 2 weeks, but no guarantees.

**Pull request merged**
