### PR TITLE
feat(extend): custom asymmetric matchers

### PR DESCRIPTION
**Pull request by muhqu**
#32562

### CODE REVIEW

**Comment by dgozman** [comment]
@muhqu Thank you for the PR!

We have actually fixed the regression introduced by #32366 in #32795. I've added a test for asymmetric matches to make sure it won't regress in the future in #32829.

That said, we are not really sure this is the API we would love to support long-term, therefore we don't want to add types support for it right now. We'll think about the API as a part of #32562.

I think we can close this PR right now, unless I am missing something and there are changes we should land. Let me know if that's the case. Thank you for contributing!

**Comment by muhqu** [comment]
@dgozman okay, sounds fair. I'm glad you fixed it for backward compatibility.

However, I think you should really consider retaining the type information of asymmetric matchers. It just feels broken, if there is something supported under the hood, but not exposed via TypeScript. Are you questioning extensibility of expect() in general? … we can also take the discussion to https://github.com/microsoft/playwright/issues/32562 if that makes sense.

I've updated this PR to only include the type definition fix.

**Comment by dgozman** [comment]
@muhqu As I said, we are not sure we'd like to keep this API for asymmetric matchers going forward. It's better to keep discussion to the issue instead of the PR for future discoverability though.

**Comment by pavelfeldman** [comment]
Closing this so that we could discuss it in the issue instead.

**Pull request closed without merging**
