### PR TITLE
test(chromium): HAR missing content for JS redirect

### PR DESCRIPTION
**Pull request by rwoll**
The two new tests are identical except for the `; charset=UTF-8` bit.
You'll notice that the tests pass, except for Chromium when the charset
is specified.

NB: If you reverse the order of these tests (assuming a serial run),
all the tests pass for both browsers.

Relates https://github.com/microsoft/playwright/issues/7348

### CODE REVIEW

**Comment by rwoll** [comment]
It looks like these passed on the bots. However, if you run locally via `npm run test` they consistently fail (at least on macOS).

**Comment by rwoll** [comment]
@dgozman It looks like it's still passing on the bots, but here's what I get when I run locally after adding `.only` to the two tests and using `npm run test`:

```
Running 6 tests using 3 workers
  1) har.spec.ts:289:4 › [chromium] should include content for JavaScript redirects ================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "base64"
    Received: undefined

      312 |
      313 |   const content = log.entries[0].response.content;
    > 314 |   expect(content.encoding).toBe('base64');
          |                            ^
      315 |   expect(content.mimeType).toBe('text/html');
      316 |   expect(Buffer.from(content.text, 'base64').toString()).toContain('redirect content');
      317 |

        at …/playwright/tests/har.spec.ts:314:28
        at WorkerRunner._runTestWithBeforeHooks (/Users/rwoll/code/playwright/tests/config/test-runner/node_modules/@playwright/test/lib/test/workerRunner.js:333:7)


  1 failed
    har.spec.ts:289:4 › [chromium] should include content for JavaScript redirects =================
  5 passed (4s)
```

Do you get the same failure?

**Comment by rwoll** [comment]
It looks like both tests are flaky to varying degrees (and I'm either doing something wrong or there is a race in the PW or Chromium code). If you add `await page.waitForLoadState();` immediately after the goto, both tests consistently pass. Without this, we get to the end destination, so I don't think it should be necessary to have this wait in order to see the intermediate content in the HAR. Perhaps an event is coming too "late"?

**Comment by rwoll** [comment]
(looking through the harTracer code now to see if there's some assumptions of event ordering and/or timing we aren't meeting)

**Comment by rwoll** [comment]
> It looks like both tests are flaky to varying degrees (and I'm either doing something wrong or there is a race in the PW or Chromium code). If you add `await page.waitForLoadState();` immediately after the goto, both tests consistently pass. Without this, we still get to the end destination, so I don't think it should be necessary to have this wait in order to see the intermediate content in the HAR. Perhaps an event is coming too "late"?

I take that back partially—it looks like waitForLoadState doesn't totally help in the charset case.

**Comment by rwoll** [comment]
@dgozman given the following modification to harTracer.ts

```diff
diff --git a/src/server/supplements/har/harTracer.ts b/src/server/supplements/har/harTracer.ts
index b34c3fdb..295bb547 100644
--- a/src/server/supplements/har/harTracer.ts
+++ b/src/server/supplements/har/harTracer.ts
@@ -225,7 +225,7 @@ export class HarTracer {
       const promise = response.body().then(buffer => {
         harEntry.response.content.text = buffer.toString('base64');
         harEntry.response.content.encoding = 'base64';
-      }).catch(() => {});
+      }).catch((err) => { console.error(response.url(), err); });
       this._addBarrier(page, promise);
     }
   }
```

whenever the test fails, we get the following error when trying to get the body:

```
http://localhost:8907/js-redirect Protocol error (Network.getResponseBody): No resource with given identifier foundError
    at /Users/rwoll/code/playwright/src/server/chromium/crConnection.ts:174:56
    at new Promise (<anonymous>)
    at CRSession.send (/Users/rwoll/code/playwright/src/server/chromium/crConnection.ts:173:12)
    at Response.getResponseBody [as _getResponseBodyCallback] (/Users/rwoll/code/playwright/src/server/chromium/crNetworkManager.ts:284:43)
    at /Users/rwoll/code/playwright/src/server/network.ts:392:21
```

(It looks like doing 10 repeats of charset test locally is enough to find a mix of passes and failures.)

**Review by pavelfeldman — APPROVED** [review]

**Comment by pavelfeldman** [comment]
I approved before reading the thread and seeing the bots. Might be easier to fix and test rather that trigger the error?

**Comment by rwoll** [comment]
Agreed—will close this for now. There's an issue, but it's turning out to be flaky so not sure we can have a great test for it on the bots.

**Pull request closed without merging**
