### PR TITLE
fix(types): fixed `Fixtures` type to disambiguite between intersected mapped types

### LINKED ISSUE #33763: [Bug]: Types for fixtures are broken in TypeScript 5.7.2
### Version

1.49.0

### Steps to reproduce

Clone this repro, run `pnpm i` and see the issue in the example test.
https://github.com/mrmckeb/pw-repro

### Expected behavior

Fixtures should work as they did in TypeScript 5.6.3.

The fixture in this example is copy-pasted from the Playwright docs, but I found this within our project with more complex fixtures in use.

### Actual behavior

Fixtures now throw type errors, with values seemingly being `any`.

Confusingly, the JSDoc shows up correctly.
Image

### Additional context

**This may be a TypeScript issue, and I'm happy to re-open there if that's the case.**

I did look for related issues earlier and didn't find any.

### Environment

```shell
System:
    OS: macOS 14.7.1
    CPU: (8) arm64 Apple M3
    Memory: 477.89 MB / 24.00 GB
  Binaries:
    Node: 18.14.0 - ~/.local/state/fnm_multishells/66817_1732588561643/bin/node
    npm: 9.3.1 - ~/.local/state/fnm_multishells/66817_1732588561643/bin/npm
    pnpm: 9.14.2 - ~/.local/state/fnm_multishells/66817_1732588561643/bin/pnpm
  IDEs:
    VSCode: 1.95.3 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/playwright/issues/33763
context behind the change can be found here: https://github.com/microsoft/TypeScript/issues/60619#issuecomment-2503967944
cc @dgozman

### CODE REVIEW

**Comment by Andarist** [comment]
I ran a different set of tests locally and missed this before opening the PR. I'll look into the reported failure soon. FWIW, the failures are related to this piece of code:
https://github.com/microsoft/playwright/blob/f3ae940684dd26de1d4674d66dd98b8722b08d50/tests/playwright-test/types.spec.ts#L110-L117

**Comment by dgozman** [comment]
Thank you for the PR, this looks fantastic!

> I ran a different set of tests locally and missed this before opening the PR. I'll look into the reported failure soon. FWIW, the failures are related to this piece of code:

I applied your suggestion to replace `KeyValue` with `{}` and that makes this test pass locally for me. Let's see what the bots think: https://github.com/microsoft/playwright/pull/33784. Also works in [this playground](https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241126#code/KYDwDg9gTgLgBDAnmYcAqwDOMBiBLEGAVymAB4AlAGjgEEoBzTOUGYAOwBNmBvAXwB8cALxwAFACg4cAIaNMALjryqUuEUzAlYqEooBKEUIAKUCAFs8msgDcIeTgNWHhQme0QBuCRKQp0WLgExKQAajIANkTk1MpMLIQc3HD8QsJqAD5wAKIgAMZRnDE0OETseTB4EOwCmQHY+IQkxXGYAt6+yKiNIVhkaAlsXLx8Iil8NMYDrEkjY6nzagDaANJweOxwANbAiBAAZnBTALoA-EoYDcHN4VHkU6vHNAMAZEdo7RKjbzzLaxvbXYHdCyZi5ApEIpkFY0HZ7Q5TARnC6BHo3SLRfqPZ5wN6I7x8DobNhQfYyPKoS4wNBdfqBejxGbDcZCX7SJmcfqDWYsyTSaT7a6kRRwNHC-rPenyJxqfQo7A0lB07AM5hvD4EnzE4Ck8moYwyBioNksGwYmRsbTYXRwa0bBguExmSzWMpbdgQADuNU1EiKBTkqDy1WwcAARjJNPLqbSeHAwIatEdE3BBB1g+xQ0UoHgbMBOGMI5oAHQcsQmhNGpSRxDlcRxyuoPiO8aqZsdbO5-OlxJcMhx8yIMVJu3sBipgTltSD4fVzC1vL1+MpibqTQtk3SGSemR4eAaYBiADkMjDeSP+m80gmX30PlAkFg428QA).

**Comment by Andarist** [comment]
@dgozman I already included the constraint fix here too :)

**Comment by Andarist** [comment]
> Per the linked issue, this only works if downstream users use TS 5.6+, right?

Yes. I don't think there is a suitable way to rewrite those types that would support older TS versions. `typesVersions` exist for a reason - but, I won't lie, they are not exactly easy to set up.

One idea to rewrite this would be to avoid reverse mapped type inference here *somehow* while preserving the contextual typing capabilities. Having that inference here isn't particularly desired and it doesn't quite work today *anyway* in this case.

**Comment by Andarist** [comment]
I came up with this *beautiful* hack that makes it work: [TS playground](https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241127#code/CYUwxgNghgTiAEYD2A7AzgF0ajIAeGArlBACoCeADgJYoDmAElGANYBc8hK1AjoQmnIBbAEZIIAKAkYqCANIhyANRL94AXngBveAG0Wijphi06AXQ5QU5eAF8A3FPyUkMLDMoJSITADFqBIRwADwASgA08ACCMHRo8Pi4KMDxCsqqIAB8GvAAFBLw8LBxHDFx4QWcaCAcuTAcoQCUGtkACjBIQtTVwQBuSNTAmRXN6tlW5I7SsvD+gXBowaQJBCDJqYoqEGqaWraRrcuJaynwaVs72rbZu5W6cvC08AbkSABm8IdmAPxslYUAH3g3j8ASIIUO9zMkWWADJPqRMv94EDdCCMHNwSBgpC5NDgfB4Ydhtp4BhqEIQEhCBhfvAUIRRCAYCjOMkQG9aCBgHYzI5bITtHcHk8Xu8CVBUqyPFSPsgULhAiQKDR6ExWD8-oVAcCfBiwUFsaQoTDBcTkaj0ZjDUsTQSiYjIjpyZTqbSOAymSygVxQJyUNzefyprRcDA3swvHqVUa9WV4sd1mdNhlslpKongEsVklTudU-ltfBOfMfBxrQsljC47E0MNKo0OOiY0sa3FBYj+VJQ8yI2AEK0oHQEOnCiBeqooLhasYjBgTPRRm0Ol0elwWCgkAB3FCZLsSUCQWAIeWYeAiSU1XWYFs6ShDq+D4d2PdSC-VAB0mdyo-g9+HliCCgYB5HeD52EuVwVLYjRTM4rhYHsjhAA). Further testing would be required to make sure that it doesn't break anything but it looks really promising to me.

The idea behind this workaround is that properties of remapping mapped types don't contribute to contextual typing. This matches the pre-5.7 behavior for this particular scenario. So by ensuring that our `as` clause remaps the property by adding a dummy symbol in its "output" we make it works again. Given this symbol is completely private, I think it won't cause much harm... although it could impact type portability for the declaration emit. That could likely be addressed by `Omit`ing it in the returned type if it even gets inferred as `T`'s property (in the playground above it doesn't so this portability argument might just not be relevant to this situation after al).

**Comment by Andarist** [comment]
> That said, we have to support at least TypeScript 5.0, so I'd prefer to avoid typesVersions if possible.

I mean, `typesVersions` is how you can support many different TS versions by providing different typing files for each of them. So that's exactly what could be used here if we don't find a suitable workaround. But also, I don't really recommend it because it would raise the complexity of your setup considerably ;p

>  Given that, I've replaced keyof T as Exclude<...> with Exclude<keyof T, ...> in hope that would somewhat work in earlier TS versions. IIUC, that would not infer as good, but at least it may prevent any or wrong type being taken for overridden fixtures.

It turns out that I confused myself here altogether. Both `keyof T as Exclude<...>` and `Exclude<keyof T, ...>` should do the trick for TS 5.0+. 

It's correct to say that `keyof T as Exclude<...>` only works since TS 5.6 but that's when that mapped type is **not** intersected with other types.

All of this works based on subtle fact that you have this mix of known/resolved properties with properties of a type that is still generic. In such an intersection case, TS (before 5.7) would just ignore the generic mapped part of the intersection when providing a contextual type and would only use the more "concrete" part of the type. This wasn't consistent because in non-intersection cases it wouldn't ignore the generic mapped part at all, it would use it. 

Fixing that had an unfortunate effect of breaking your types. But at the same time, it means that it doesn't quite matter how you write those generic mapped types here... because pre TS 5.7 they will just be ignored when selecting the contextual type.

**Comment by dgozman** [comment]
Closing in favor of #33784, thank you for all the help!

**Pull request closed without merging**
