### PR TITLE
chore: add eslint cache

### PR DESCRIPTION
**Pull request by winchesHe**
add eslint cache

### CODE REVIEW

**Comment by winchesHe** [comment]
> @winchesHe please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by pavelfeldman** [comment]
Could you link to an issue or include an explanation of what is happening and why?

**Comment by winchesHe** [comment]
>

**Comment by winchesHe** [comment]
> Could you link to an issue or include an explanation of what is happening and why?

It can avoid checking duplicate files to improve execution speed

run eslint without cache

image

run eslint with cache

image

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
