### PR TITLE
fix(docs): ava example, missing the context object

### PR DESCRIPTION
**Pull request by bitcoder**
the previous example doesnt work out. Maybe other examples for the remaining test runners have also to be updated

### CODE REVIEW

**Comment by bitcoder** [comment]
Maybe the online docs also need to be updated at https://playwright.dev/#version=v1.0.1&path=docs%2Ftest-runners.md&q=ava

**Comment by JoelEinbinder** [comment]
Thanks for the PR. `browser.newPage()` actually already creates a new context for that page, so these pieces of code are equivalent.

> Maybe the online docs also need to be updated at https://playwright.dev/#version=v1.0.1&path=docs%2Ftest-runners.md&q=ava

That website is automatically generated from the docs, so it gets updated whenever you change the docs here! 🥳

**Comment by bitcoder** [comment]
Hi again,
well, if I used it as you said.. it doesn't work out.

```
const {chromium} = require('playwright');
const test = require('ava').default;
const browserPromise = chromium.launch();

async function pageMacro(t, callback) {
  const browser = await browserPromise;
//  const context = await browser.newContext();
  const page = await browser.newPage();

  try {
    await callback(t, page);
  } finally {
    await page.close();
  }
}

test('should work', pageMacro, async (t, page) => {
  await page.goto('https://www.example.com/');
  t.is(await page.title(), 'Example Domain');
});
```

Which leads to



```
  test/example_site.js:8

   7: //  const context = await browser.newContext();
   8:   const page = await browser.newPage();
   9:

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'browser.newPage is not a function',
  }

  › pageMacro (test/example_site.js:8:30)


```

**Comment by JoelEinbinder** [comment]
What version of playwright are you using? `browser.newPage` has been a function since v0.11.0.

**Comment by bitcoder** [comment]
you are right; I've updated it and it works as you said. thanks!

**Pull request closed without merging**
