### PR TITLE
WIP: init Video recorder

### PR DESCRIPTION
**Pull request by vitalics**
Add video recording support.
Recording with the headless browser(xfvb)
Will be useful for CI failures(#1914 )
API:
``` ts
startVideo(options: Options) => Promise<void> // start record video with selected options
stopVideo() => Promise<Buffer> // stop recoding video
```
where
``` ts
type Options = {
outFile?: string // should include file extension, e.g. video.mp4. Be default generate unique filename
keepScreenshots?: boolean // keep making screenshots after video stopped. Default is false
FPS?: 60 | 30 // output fps. Default is 30
}
```
TODO: 
1) fix golden compare function related videos
2) add a description in API docs
3) add video information(e.g. duration, meta information, etc.) 

P.S. any help will be useful

### CODE REVIEW

**Comment by dgozman** [comment]
Thank you for the fantastic PR! This is indeed one of our top priorities - you've already pointed to #1914.

We are currently working on the screencast/frames retrieval across the browsers. The approach of periodically taking screenshots might not work in some setups. Mind giving us some time to wrap up the screencast implementation?

Then we can follow up with making it into a nice video API, something similar to this PR. I think that video generation part is especially interesting here, we'll definitely get back to this soon.

**Comment by vitalics** [comment]
@dgozman Thanks for the feedback. Actually I have other ideas with playwright. I'm at stalled for video since I haven't an idea how to do video better. Of course, I'll be waiting for the screencast implementation.
Could you please add a comment to this PR when screencast API will be ready.

**Comment by dgozman** [comment]
> Could you please add a comment to this PR when screencast API will be ready.

Sure!

**Comment by aslushnikov** [comment]
We're working on an upstream screencast support in browsers and it looks promising so far. I'll close this PR for now as part of the summer cleaning.

@vitalics Thank you for the PR though! It sparked a lot of discussions internally in the team! :)

**Pull request closed without merging**
