### PR TITLE
chore(installer): added allowlist for browser installer

### PR DESCRIPTION
**Pull request by mxschmitt**
Original issue in Playwright Python: https://github.com/microsoft/playwright-python/issues/47

**Description**
Some users on their local machine or on CI/bot systems don't want to install all the browsers while using the RPC clients. Currently we call `installBrowsersWithProgressBar()` for installing the browsers which installs all the browsers since we have a full `browsers.json`, see [here](https://github.com/microsoft/playwright-python/blob/9c8ca93ae6e78209987f5545006de4272a500da0/driver/main.js#L26).

My idea was to have an optional CLI argument in the linked main.js which we pass to the function and acts as an allowlist. If none is specified no filtering will be made. Only if > 0 is passed filtering is applied.

Maybe there is a better API design for that, let me know. 🙂

cc @dgozman

### CODE REVIEW

**Comment by pavelfeldman** [comment]
Could you share more about how you intend to use it? I don't want to encourage the chromium-only use on the client, while the cloud might benefit from a different (env-based) solution that works for all languages including Node.

**Comment by mxschmitt** [comment]
> Could you share more about how you intend to use it? I don't want to encourage the chromium-only use on the client, while the cloud might benefit from a different (env-based) solution that works for all languages including Node.

I thought that the user will execute in the end:

```bash
python -m playwright install webkit
```

which spawns the subprocess as we currently have implemented and passes its argument to the function as proposed [here](https://github.com/microsoft/playwright-python/pull/121).

**Comment by pavelfeldman** [comment]
So this is to save 300 Mb to those that would only want to use Chromium? Chromium-only implies enterprise or automation application rather than web testing. For the greater Web, we'd like to encourage testing on all vendors.

Single create-react-app / Jest install is comparable to that Mb amount, per project, while Playwright shares installs. I'd like to better understand why users would want to opt out of WebKit on their local setups. Maybe they need something else, or maybe they don't need Playwright at all?

**Comment by mxschmitt** [comment]
TBD first.

**Pull request closed without merging**
