### PR TITLE
test: fixed failing test on video bot

### PR DESCRIPTION
**Pull request by mxschmitt**
Caused by #4736 reverted my change.

@dgozman  (https://github.com/microsoft/playwright/pull/4736#issuecomment-747105121)

### CODE REVIEW

**Review by dgozman — APPROVED** [review]
I think I also saw `should be able to capture alert` failing.

**Comment by mxschmitt** [comment]
> I think I also saw `should be able to capture alert` failing.

do you have an idea why this change needs to be reverted? Weird behaviour for me, even that this is passing with the normal tests.

**Comment by dgozman** [comment]
> do you have an idea why this change needs to be reverted? Weird behaviour for me, even that this is passing with the normal tests.

No, not really. Probably needs investigation.

**Comment by dgozman** [comment]
Should we land this?

**Comment by mxschmitt** [comment]
> Should we land this?

Would say yes, reverted the relevant changes which I did.

**Pull request merged**
