### PR TITLE
chore: test for consistent resource timing values

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ adds tests for #8636

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Thanks for the quick fix @yury-s, Added tests for the same since i already had them.

**Comment by vigneshshanmugam** [comment]
Tests fail on WebKit, could this be a WebKit bug with RT dada? @yury-s @pavelfeldman ?

**Comment by pavelfeldman** [comment]
It most likely is, let's see other platforms.

**Comment by vigneshshanmugam** [comment]
Tried debugging this on webkit, event.timestamp values were wrong for the `loadingFinished` event. Even though the `responseReceived` fires before the `loadingFinished`, the event timestamp value for `responseReceived` is higher than that of `loadingFinished`. 

```
_onResponseReceived -  43.539 ms
_onDataReceived  - 44.039 ms
_onLoadingFinished -  42.445 ms
```

Should we skip this test on webkit?

**Comment by aslushnikov** [comment]
Filed an issue if we ever want to tackle this: https://github.com/microsoft/playwright/issues/11986

Closing for now.

**Pull request closed without merging**
