### PR TITLE
fix(prepare): Add --no-sandbox argument

### PR DESCRIPTION
**Pull request by kblok**
I don't know if this is the right thing to do. But I had to add this to run `sudo npm run prepare` and  `generate-types`

### CODE REVIEW

**Comment by kblok** [comment]
@pavelfeldman MacOS 10.15 Nodejs 12
It was this validation https://github.com/microsoft/playwright/blob/8f0f32b5e60b5abaa209bfcd181b2f6424b5b8b1/src/server/chromium.ts#L57

**Comment by aslushnikov** [comment]
Oh, looks like our "runningAsRoot" didn't work

Did you use "sudo" or something?

**Comment by kblok** [comment]
@aslushnikov I did use `sudo`.

**Comment by aslushnikov** [comment]
Discussed this offline with Dario! Short summary: using `sudo` while doing `npm install` will yield us in a bad place.

The solution is to avoid using `sudo` for npm scripts.

**Pull request closed without merging**
