### PR TITLE
fix(chromium): remove Debugger.paused event listener on coverage stop

### LINKED ISSUE #3250: [BUG] Memory leak in chromium test coverage
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.2.1
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 10.12, 10.14] 14.1.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const playwright = require("playwright");

async function run() {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();

  for (let i = 0; i < 100; i++) {
    await page.coverage.startJSCoverage();
    await page.goto("https://www.example.com/");
    await page.coverage.stopJSCoverage();
  }

  browser.close();
}

run();
```

You will see a warning logged about too many listeners being registered.

**Describe the bug**

There is an event listener registered on coverage start: https://github.com/microsoft/playwright/blob/master/src/chromium/crCoverage.ts#L83 but it's not cleared on coverage stop. This causes a memory leaking when coverage is started/stopped multiple times for a single page.

### PR DESCRIPTION
**Pull request by LarsDenBakker**
Fixes https://github.com/microsoft/playwright/issues/3250

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
The test failure seems unrelated to this change. Is there a way to re-run it?

**Comment by dgozman** [comment]
> The test failure seems unrelated to this change. Is there a way to re-run it?

I just restarted the checks.

**Review by dgozman — APPROVED** [review]
Great! Thank you for the PR.

**Comment by LarsDenBakker** [comment]
Another test failed now :(

**Comment by dgozman** [comment]
> Another test failed now :(

That's alright, we are in the process of figuring out video tests :)

**Pull request merged**
